---
title: "Dataset D2"
author: "Denise Ong"
date: "9/15/2021"
output: html_document
---
# Initialize
```{r, echo=TRUE, message=FALSE, warning=FALSE}

source("phyloseq/init.R") #for libraries
source("phyloseq/init_markdown.R") #for markdown libraries
source("phyloseq/define_functions.R") #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps 
```

#C14 syn - to Subclade level
```{r}
# Read data

# Load the phyloseq files
ps <- read_rds("output_petb_2x300/output_petb_nested/TAN1810_petB_nestedphyloseq_asv_set_D2.1.RDS") 

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps)$water_mass <- sample_data(ps)$Cycle.
sample_data(ps)$water_mass = str_replace(sample_data(ps)$water_mass, "1|2|5", "SA") 
sample_data(ps)$water_mass = str_replace(sample_data(ps)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps)$cycle_location <- sample_data(ps)$Cycle.
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "1", "C")
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "2", "D") 
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "5", "E") 
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "3", "A")
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "4", "B")

sample_data(ps)$cycle_name <- sample_data(ps)$Cycle.
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps)$cycle_location_name <- str_c(sample_data(ps)$cycle_location, sample_data(ps)$cycle_name, sep ="_")

#vial type
sample_data(ps)$vial_type <- sample_data(ps)$vial
sample_data(ps)$vial_type = str_replace(sample_data(ps)$vial_type, "i", "initial") 
sample_data(ps)$vial_type = str_replace(sample_data(ps)$vial_type, "A|B|C", "light")
sample_data(ps)$vial_type = str_replace(sample_data(ps)$vial_type, "D", "dark")

# Remove ASVs that are not present in the dataset
ps <- ps %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps <- phyloseq_normalize_median(ps)
long <- phyloseq_transform_to_long(ps)
source("phyloseq/colours.R") # for colours, using Rcolourbrewer
```


```{r}
p <- long %>%
    mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "syn-negr1-2") %>%
    filter(sample_name != "syn-11") %>%
    filter(sample_name != "syn-12") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
        theme(text=element_text(size=10),axis.text.x = element_text(angle = 45, hjust = 1)) + 
    #    facet_grid(.~water_mass, scales = "free_x") +
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("C14 sorted syn") +
        scale_color_manual(values=subcladePalette, limits = force) + 
        scale_fill_manual(values=subcladePalette, limits = force)
p

pdf("phyloseq/figures/20210916_C14 syn merged.pdf", height=5, width=8) ; plot(p) ; dev.off()
```
# CTD- petB nested Read data
```{r}
# Load the phyloseq files
ps_ctd_nested <- read_rds("output_petb_2x300/output_petb_nested/TAN1810_petB_nestedphyloseq_asv_set_D2.2.RDS") 

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_ctd_nested)$water_mass <- sample_data(ps_ctd_nested)$cycle
sample_data(ps_ctd_nested)$water_mass = str_replace(sample_data(ps_ctd_nested)$water_mass, "1|2|5", "SA") 
sample_data(ps_ctd_nested)$water_mass = str_replace(sample_data(ps_ctd_nested)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_ctd_nested)$cycle_location <- sample_data(ps_ctd_nested)$cycle
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "1", "C")
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "2", "D") 
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "5", "E") 
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "3", "A")
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "4", "B")

sample_data(ps_ctd_nested)$cycle_name <- sample_data(ps_ctd_nested)$cycle
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps_ctd_nested)$cycle_location_name <- str_c(sample_data(ps_ctd_nested)$cycle_location, sample_data(ps_ctd_nested)$cycle_name, sep ="_")

# Remove ASVs that are not present in the dataset
ps_ctd_nested <- ps_ctd_nested %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_ctd_nested <- phyloseq_normalize_median(ps_ctd_nested)
long_ctd_nested <- phyloseq_transform_to_long(ps_ctd_nested)
```


```{r}
p <- long_ctd_nested %>%
    mutate(Subclade = fct_infreq(Subclade))%>%
   # filter(sample_name != "syn-negr1-2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
        theme(text=element_text(size=10),axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB nested merged - subclade") +
        scale_color_manual(values=subcladePalette, limits = force) + 
        scale_fill_manual(values=subcladePalette, limits = force)
p

pdf("phyloseq/figures/20210916_C14 petb nested merged.pdf", height=5, width=8) ; plot(p) ; dev.off()
```

# CTD- petB normal Read data
```{r}
# Load the phyloseq files
ps_ctd_normal <- read_rds("output_petb_2x300/output_petb_normal/TAN1810_petB_normal_phyloseq_asv_set_D3.RDS")  # adding new component, this case the phyloseq object to the "tag" all

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_ctd_normal)$water_mass <- sample_data(ps_ctd_normal)$cycle
sample_data(ps_ctd_normal)$water_mass = str_replace(sample_data(ps_ctd_normal)$water_mass, "1|2|5", "SA") 
sample_data(ps_ctd_normal)$water_mass = str_replace(sample_data(ps_ctd_normal)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_ctd_normal)$cycle_name <- sample_data(ps_ctd_normal)$cycle
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "4", "ST-Cycle_4")


# Remove ASVs that are not present in the dataset
ps_ctd_normal <- ps_ctd_normal %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_ctd_normal <- phyloseq_normalize_median(ps_ctd_normal)
long_ctd_normal <- phyloseq_transform_to_long(ps_ctd_normal)
```

```{r}
p <- long_ctd_normal %>%
    mutate(Subclade = fct_infreq(Subclade))%>%
   # filter(sample_name != "syn-negr1-2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
        theme(text=element_text(size=10),axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_grid(.~cycle_name, scales = "free_x") +
        ggtitle("CTD petB normal R1 - subclade") +
        scale_color_manual(values=subcladePalette, limits = force) + 
        scale_fill_manual(values=subcladePalette, limits = force)
p
```