---
title: "Chlorophyll"
author: "Denise Ong"
date: "3/19/2021"
output: html_document
---
```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

```{r}

library(tidyverse)
library(ggplot2)
library(broom)
library(ggpubr)
library(stringr)
library(RColorBrewer)
library(dplyr)
```

```{r}
chl_raw <- readxl::read_excel("data_used/TAN1810_SFChla.xls") %>%
  select(U_Cast, Depth,  Chla_0.2:Chla_20_pct)%>%
  filter(!is.na(U_Cast))
chl_raw$U_Cast<-as.character(chl_raw$U_Cast)
#for cycle number
NPP_raw <- readxl::read_excel("data_used/TAN1810_NPP_areal.xlsx") %>%
  select(Cycle, Station, U_Cast) %>%
  distinct()

chl_raw <- left_join(chl_raw,NPP_raw)
chl_raw

check <- chl_raw %>%
  select(U_Cast, Cycle) %>%
  distinct()
check
# Many ctd cast without cycle number,  cannot find in voyage report. To check

chl_subset <- chl_raw %>%
  filter(!is.na(Cycle))%>%
  mutate(cycle_name = recode(Cycle, "1" = "SA 1",
                                    "2" = "SA 2",
                                    "3" = "ST 1",
                                    "4" = "ST 2",
                                    "5" = "SA 3")) %>%
  mutate(cycle_name = fct_relevel(cycle_name, 
            "ST1", "ST2", "SA1", 
            "SA2", "SA3"))%>%
  filter(!is.na(Chla_2)) %>%
  filter(!is.na(Chla_20))
chl_subset
```

```{r}

frac_chl_pct_summary <- chl_subset %>%
  dplyr::group_by(cycle_name) %>%
  summarise("Pico: 0.2-2 um" = mean(Chla_0.2_pct),
            "Nano: 2-20 um" = mean(Chla_2_pct),
            "Micro: >20 um" = mean(Chla_20_pct)) %>%
  pivot_longer("Pico: 0.2-2 um":"Micro: >20 um",
               names_to = "fraction",
               values_to = "pct") 
frac_chl_pct_summary

frac_chl_pct_summary$cycle_name<-as.character(frac_chl_pct_summary$cycle_name)
frac_chl_pct_summary$cycle_name <- factor(frac_chl_pct_summary$cycle_name, levels = c("ST1", "ST2", "SA1", "SA2", "SA3"))

frac_chl_pct_summary

frac_chl_plot <- frac_chl_pct_summary %>%
 #dplyr::mutate(cycle_name = forcats::fct_relevel(cycle_name, "ST1", "ST2", "SA1", "SA2", "SA3"))%>%
  ggplot(aes(x=cycle_name, y=pct, fill=factor(fraction, levels = c("Micro: >20 um", "Nano: 2-20 um", "Pico: 0.2-2 um"))))+
  geom_bar(stat="identity") +
  scale_fill_brewer(palette = "Dark2")+
  theme_bw()+
  ylab("TChl a (%)")+
  xlab("Cycle")+
  labs(fill="Size fraction")
frac_chl_plot
```

#Function for summarising the data
```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```



```{r}

chl_summary <- summarySE(chl_subset, measurevar="SumSFChla", groupvars=c("cycle_name"), na.rm=TRUE)
chl_summary


frac_chl_summary <- chl_subset %>%
  dplyr::group_by(cycle_name) %>%
  summarise("Pico: 0.2-2 um" = mean(Chla_0.2),
            "Nano: 2-20 um" = mean(Chla_2),
            "Micro: >20 um" = mean(Chla_20)) %>%
  pivot_longer("Pico: 0.2-2 um":"Micro: >20 um",
               names_to = "fraction",
               values_to = "chl")
frac_chl_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

chl_summary$cycle_name<-as.character(chl_summary$cycle_name)
chl_summary$cycle_name <- factor(chl_summary$cycle_name, levels = c("ST1", "ST2", "SA1", "SA2", "SA3"))

frac_chl_summary$cycle_name<-as.character(frac_chl_summary$cycle_name)
frac_chl_summary$cycle_name <- factor(frac_chl_summary$cycle_name, levels = c("ST1", "ST2", "SA1", "SA2", "SA3"))

chl_summary_plot <- ggplot()+
  geom_errorbar(data=chl_summary, aes(ymin=SumSFChla-sd, ymax=SumSFChla+sd, x= cycle_name), width=.1, position=pd) +
  geom_bar(data = frac_chl_summary, aes(x=cycle_name, y= chl, fill=factor(fraction, levels = c("Micro: >20 um", "Nano: 2-20 um", "Pico: 0.2-2 um"))), stat="identity")+
  theme_bw() +
  scale_fill_brewer(palette = "Dark2")+
  ylab("TChl a (mg m-3)")+
  xlab("Cycle")+
  labs(fill="Size fraction")

chl_summary_plot
```

```{r}
library(cowplot)
chl_combined <- plot_grid(
  chl_summary_plot+ theme(legend.position="none"),
  frac_chl_plot+ theme(legend.position="none"), 
  labels = c("A", "B"), 
  align = 'vh',
  hjust = -1,
  nrow = 1) 

# extract a legend that is laid out horizontally
legend_b <- get_legend(
  chl_summary_plot + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
chl_combined <- plot_grid(chl_combined, legend_b, ncol = 1, rel_heights = c(1, .1))

chl_combined
ggsave("../figures/QE_chl combined.png")
```

