---
title: "ACOP poster figure"
author: "Denise Ong"
date: "3/11/2021"
output: html_document
---

Poster figure for ACOP. C14 group rates. using method 2 - calculate rate per vial. 
  filter(!(cycle == "4"& exp == "9"& depth == "DCM"& population == "Nano"& vial == "B")) %>%
  filter(!(cycle == "1"& exp == "2"& depth == "SUR"& population == "Pico"& vial == "A")) 

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(here)
source(here("init_files", "init.R")) #for libraries
source(here("init_files", "init_markdown.R")) #for markdown libraries
```
#Colours for cycle
```{r}
colours_cycle <- readxl::read_excel("colours_cycle.xlsx")
colours_cycle <- structure(colours_cycle$colour,.Names=colours_cycle$cycle)
```

# Read data
```{r}
cold_standard <- readxl::read_excel("group_rates_output/NPP_cold_standard.xlsx") %>% 
  rename(depth_m = `depth`,
         depth = `sample`)
cold_standard$exp <- as.character(cold_standard$exp)
pp_rates <- readxl::read_excel("group_rates_output/Rates_cell_npp_method2.xlsx")
```



# pp rates per cell
```{r}
pp_rates <- pp_rates %>%
  filter(!(cycle == "4"& exp == "9"& sample == "DCM"& population == "Nano"& vial == "B")) %>%
  filter(!(cycle == "1"& exp == "2"& sample == "SUR"& population == "Pico"& vial == "A")) %>%
  mutate(water_depth = str_c(water_mass, depth_cat, sep = "_"))
```



```{r}
pp_rates$water_mass <- factor(pp_rates$water_mass, levels = c("ST", "SA"))
pp_rates$cycle_name <- factor(pp_rates$cycle_name, levels = c("ST1", "ST2", "SA1", "SA2", "SA3"))
pp_rates$population_name <- factor(pp_rates$population_name, levels = c("Synechococcus", "Picoeukaryotes", "Nanoeukaryotes"))
pp_rates$population <- factor(pp_rates$population, levels = c("Syn", "Pico", "Nano"))
#pp_rates$depth_cat <- factor(pp_rates$depth_cat, levels = c("Surface", "DCM"))
p1 <- pp_rates %>%
  ggplot(aes(x = population, y = pp, color = cycle_name, shape = depth_cat))  +
  geom_jitter(width = 0.05) +
  xlab("Phytoplankton group") +
  ylab(expression(Primary~Production~(fgC~cell^-1~h^-1))) +
  theme_bw() +
  #facet_grid(.~ water_mass) +
  scale_color_manual(values = colours_cycle, name = "Station") +
  scale_shape_discrete(name = "Depth") +
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l") 
p1

p2 <- pp_rates %>%
  ggplot(aes(x = population, y = pp))  +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(color = cycle_name, shape = depth_cat), width = 0.1) +
  xlab("Phytoplankton group") +
  ylab(expression(Primary~Production~(fgC~cell^-1~h^-1))) +
  theme_bw() +
  facet_grid(.~ water_mass) +
  scale_color_manual(values = colours_cycle, name = "Station") +
  scale_shape_discrete(name = "Depth") +
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l") 

p2

p3 <- pp_rates %>%
  ggplot(aes(x = water_mass, y = pp))  +
#  geom_violin()+
# geom_boxplot(outlier.shape = NA) + 
  geom_jitter(aes(color = cycle_name, shape = depth_cat), width = 0.1) +
  geom_boxplot(width=0.5, alpha = 0)+
  #geom_boxplot(width=0.5, alpha = 0, color = "#424242")+
  xlab("Water mass") +
  ylab(expression(Primary~Production~(fgC~cell^-1~h^-1))) +
  theme_bw() +
  facet_grid(.~ population) +
  scale_color_manual(values = colours_cycle, name = "Station") +
  scale_shape_discrete(name = "Depth") +
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l") +
  theme(legend.position="bottom", 
       panel.spacing.x = unit(0,"line"))

p3
#pdf("figures/GRC/pp_rates_group_2.pdf", height=4, width=6) ; plot(p3) ; dev.off()


p4 <- pp_rates %>%
  ggplot(aes(x = sample, y = pp))  +
#  geom_violin()+
# geom_boxplot(outlier.shape = NA) + 
  geom_jitter(aes(color = cycle_name, shape = depth_cat), width = 0.2) +
  geom_boxplot( alpha = 0)+
  #geom_boxplot(width=0.5, alpha = 0, color = "#424242")+
  xlab("Water mass") +
  ylab(expression(Primary~Production~(fgC~cell^-1~day^-1))) +
  theme_bw() +
  facet_grid(.~ population) +
  scale_color_manual(values = colours_cycle, name = "Station") +
  scale_shape_discrete(name = "Depth") +
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l") +
  theme(legend.position="bottom", 
       panel.spacing.x = unit(0,"line"))
p4

#pdf("figures/GRC/pp_rates_group.pdf", height=4, width=6) ; plot(p4) ; dev.off()

```

```{r}
table <- read.csv("filt_subclade_percent_wide_summary_2.0.txt", sep = "\t")
library(xtable)
print(xtable(table),
      comment = FALSE,
      include.rownames=FALSE,
      digits=-3)

```


```{r}
fcm_corrected$cycle_name<-as.character(fcm_corrected$cycle_name)
fcm_corrected$cycle_name <- factor(fcm_corrected$cycle_name, levels = c("ST1", "ST2", "SA1", "SA2", "SA3"))
fcm_corrected$population_name <- factor(fcm_corrected$population_name, levels = c("Synechococcus", "Picoeukaryotes", "Nanoeukaryotes"))
fcm_corrected$population <- factor(fcm_corrected$population, levels = c("Syn", "Pico", "Nano"))
fcm_corrected$water_mass <- factor(fcm_corrected$water_mass, levels = c("ST", "SA"))

p5 <- fcm_corrected %>%
  ggplot(aes(x = population_name, y = npp, color = cycle_name, shape = sample))  +
  geom_jitter(width = 0.05) +
  xlab("Phytoplankton group") +
  ylab(expression(Net~Primary~Production~(mgC~m^3~day^-1))) +
  theme_bw() +
  #facet_grid(.~ water_mass) +
  scale_color_manual(values = colours_cycle) +
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l")

p5

p4 <- fcm_corrected %>%
  ggplot(aes(x = population_name, y = npp)) +
  geom_boxplot() + 
  geom_jitter(aes(color = cycle_name, shape = sample), width = 0.1) +
  scale_color_manual(values = colours_cycle) +
  ylab(expression(Net~Primary~Production~(mgC~m^3~day^-1)))+
  theme_bw() +
  facet_grid(.~ water_mass) +
  #xlab("Cycle")+
  scale_y_continuous(trans='log10')+
  annotation_logticks(sides = "l")
p4

p6 <- fcm_corrected %>%
  ggplot(aes(x = water_mass, y = npp))  +
 # geom_violin()+
  #geom_boxplot(outlier.shape = NA) + 
  geom_jitter(aes(color = cycle_name, shape = sample), width = 0.1) +
  geom_boxplot(width=0.5, alpha = 0, color = "#424242")+
#  stat_summary(fun.y=median, geom="point", size=2, color="#424242")+
  xlab("Water mass") +
  ylab(expression(Net~Primary~Production~(mgC~m^3~day^-1))) +
  theme_bw() +
  facet_grid(.~ population) +
  scale_color_manual(values = colours_cycle, name = "Station") +
  scale_shape_discrete(name = "Depth") +
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l") +
  theme(legend.position="bottom")

p6
pdf("figures/pp_total.pdf", height=4, width=6) ; plot(p6) ; dev.off()
```
