---
 title: "QE_CTD and nutrients"
author: "Denise Ong"
date: "3/19/2021"
output: html_document
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               tidy = FALSE,
               fig.height=8, 
               fig.width=8,
               results = 'asis')
opts_knit$set(width=75)
```

# Load libraries

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(readxl) # Read excel file
library(lubridate) 
library("cowplot")
library("AquaEnv")
library("gsw")
library(ggsci)
library(RColorBrewer)
```

# Nutrients
# Read table, combine with C14 hot for the cycle, exp and station number.
```{r}
nutrients_raw <- readxl::read_excel("../data_used/TAN1810_nutrients.xls") %>%
  dplyr::rename(CTD = `U_Cast`,
                depth =`Depth`)

CTD_raw <- readxl::read_excel("../data_used/TK_CTD Downcasts.xlsx") %>%
  dplyr::rename(CTD = `cast`) %>%
  mutate(datetime =  dmy_hms(datetime)) %>%
  filter(!is.na(t)) %>%
  mutate(date = date(datetime)) %>%
  #mutate(time = hour(datetime)) %>%
  mutate(julian_day = julian(date, origin = date("2018-01-01"))) %>%
  select(CTD, datetime, date, julian_day) %>%
  mutate(CTD=as.character(CTD)) %>%
  distinct()

nutrients <- full_join(nutrients_raw,CTD_raw) %>%
  filter(!is.na(depth)) %>%
  filter(!is.na(julian_day)) %>%  #how to insert date for the missing dates. Corresponding CTD no. is 9167, 9171, 9169, 9168
  filter(depth<=100)
nutrients


```
```{r}
nutrients <- nutrients %>%
  mutate(cycle = NA)

nutrients$julian_day <- as.character(nutrients$julian_day)
nutrients$cycle[grep("296", nutrients$julian_day)] = "1"
nutrients$cycle[grep("297", nutrients$julian_day)] = "1"
nutrients$cycle[grep("298", nutrients$julian_day)] = "1"
nutrients$cycle[grep("299", nutrients$julian_day)] = "1"
nutrients$cycle[grep("300", nutrients$julian_day)] = "1"
nutrients$cycle[grep("301", nutrients$julian_day)] = "1"
nutrients$cycle[grep("302", nutrients$julian_day)] = "1"
nutrients$cycle[grep("305", nutrients$julian_day)] = "2"
nutrients$cycle[grep("306", nutrients$julian_day)] = "2"
nutrients$cycle[grep("307", nutrients$julian_day)] = "2"
nutrients$cycle[grep("308", nutrients$julian_day)] = "2"
nutrients$cycle[grep("309", nutrients$julian_day)] = "2"
nutrients$cycle[grep("311", nutrients$julian_day)] = "3"
nutrients$cycle[grep("312", nutrients$julian_day)] = "3"
nutrients$cycle[grep("313", nutrients$julian_day)] = "3"
nutrients$cycle[grep("315", nutrients$julian_day)] = "4"
nutrients$cycle[grep("316", nutrients$julian_day)] = "4"
nutrients$cycle[grep("317", nutrients$julian_day)] = "4"
nutrients$cycle[grep("319", nutrients$julian_day)] = "5"
nutrients$cycle[grep("320", nutrients$julian_day)] = "5"

nutrients <- nutrients %>%
  filter(!is.na(cycle)) %>%
  mutate(cycle_name = recode(cycle, "1" = "Subantarctic 1",
                                    "2" = "Subantarctic 2",
                                    "3" = "Subtropical 1",
                                    "4" = "Subtropical 2",
                                    "5" = "Subantarctic 3")) 

check <- nutrients  %>% 
  select(CTD, date, cycle) %>%
  distinct()
check
```


#Function for summarising the data
```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```

Plot nitrate

```{r}
library(viridis)
#summarise temp data
nitrate_summary <- summarySE(nutrients, measurevar="NO3_uM", groupvars=c("depth","cycle_name"), na.rm=TRUE)
nitrate_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

nitrate_plot <- nitrate_summary %>%
  ggplot(aes(x=NO3_uM, y=depth, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=NO3_uM-sd, xmax=NO3_uM+sd), width=.1, position=pd) +
    geom_path() +
    geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab(expression(paste("Nitrate (uM)")))+
  labs(colour = "Cycle name")+
  scale_color_brewer(palette = "Dark2")+
  theme(legend.title =element_text(size=12,face="bold"),
        legend.text = element_text(size=12))
 
nitrate_plot

```

Plot phosphorus

```{r}
library(viridis)
#summarise temp data
p_summary <- summarySE(nutrients, measurevar="DRP_uM", groupvars=c("depth","cycle_name"), na.rm=TRUE)
p_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

p_plot <- p_summary %>%
  ggplot(aes(x=DRP_uM, y=depth, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=DRP_uM-se, xmax=DRP_uM+se), width=.1, position=pd) +
    geom_path() +
    geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab(expression(paste("Phosphate (uM)")))+
  labs(colour = "Cycle name")+
  scale_color_jco() 
 
p_plot

```

Plot silicate

```{r}
library(viridis)
#summarise temp data
si_summary <- summarySE(nutrients, measurevar="DRSi_uM", groupvars=c("depth","cycle_name"), na.rm=TRUE)
si_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

si_plot <- si_summary %>%
  ggplot(aes(x=DRSi_uM, y=depth, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=DRSi_uM-sd, xmax=DRSi_uM+sd), width=.1, position=pd) +
    geom_path() +
    geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab(expression(paste("Silicate (uM)")))+
  labs(colour = "Cycle name")+
scale_color_brewer(palette = "Dark2")
 
si_plot

```

# CTD
# Read table.
```{r}
CTD_raw <- readxl::read_excel("../data_used/TK_CTD Downcasts.xlsx") %>%
  dplyr::rename(CTD = `cast`) %>%
  mutate(datetime =  dmy_hms(datetime)) %>%
  filter(!is.na(t)) %>%
  mutate(date = date(datetime)) %>%
  mutate(time = hour(datetime)) %>%
  mutate(julian_day = julian(date, origin = date("2018-01-01"))) %>%
  filter(time %in% (9:12) ) %>%
  mutate(t_mean = (t+t2)/2) %>%
  mutate(s_mean = (s+s2)/2) %>%
  mutate(os_mean = (os+os2)/2) %>%
  select(-t, -t2, -s, -s2, -os, -os2) %>%
  filter(p <= 100)
CTD_raw
```

```{r}
CTD <- CTD_raw %>%
  mutate(cycle = NA)

CTD$julian_day <- as.character(CTD$julian_day)
CTD$cycle[grep("297", CTD$julian_day)] = "1"
CTD$cycle[grep("298", CTD$julian_day)] = "1"
CTD$cycle[grep("299", CTD$julian_day)] = "1"
CTD$cycle[grep("300", CTD$julian_day)] = "1"
CTD$cycle[grep("301", CTD$julian_day)] = "1"
CTD$cycle[grep("302", CTD$julian_day)] = "1"
CTD$cycle[grep("305", CTD$julian_day)] = "2"
CTD$cycle[grep("306", CTD$julian_day)] = "2"
CTD$cycle[grep("307", CTD$julian_day)] = "2"
CTD$cycle[grep("308", CTD$julian_day)] = "2"
CTD$cycle[grep("309", CTD$julian_day)] = "2"
CTD$cycle[grep("311", CTD$julian_day)] = "3"
CTD$cycle[grep("312", CTD$julian_day)] = "3"
CTD$cycle[grep("313", CTD$julian_day)] = "3"
CTD$cycle[grep("315", CTD$julian_day)] = "4"
CTD$cycle[grep("316", CTD$julian_day)] = "4"
CTD$cycle[grep("317", CTD$julian_day)] = "4"
CTD$cycle[grep("319", CTD$julian_day)] = "5"
CTD$cycle[grep("320", CTD$julian_day)] = "5"

CTD <- CTD %>% mutate(cycle_name = recode(cycle, "1" = "Subantarctic 1",
                                    "2" = "Subantarctic 2",
                                    "3" = "Subtropical 1",
                                    "4" = "Subtropical 2",
                                    "5" = "Subantarctic 3")) 
#CTD$cycle_name <- factor(CTD$cycle_name,levels = c("Subtropical 1", "Subtropical 2", "Subantarctic 1", "Subantarctic 2", "Subantarctic 3")) 

CTD <- CTD %>%
    filter(!is.na(cycle)) #remove rows without cycle number

```
Plot temperature

```{r}
#summarise temp data
temp_summary <- summarySE(CTD, measurevar="t_mean", groupvars=c("p","cycle_name"), na.rm=TRUE)
temp_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

temp_plot <- temp_summary %>%
  ggplot(aes(x=t_mean, y=p, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=t_mean-sd, xmax=t_mean+sd), width=.1, position=pd) +
    geom_path() +
    geom_point(size=0.5) +
  scale_y_reverse()+
  theme_bw() +
  ylab("Depth (m)")+
  xlab(expression(paste("Temperature (",degree,"C)")))+
  labs(colour = "Cycle name")+
scale_color_brewer(palette = "Dark2")
 
temp_plot

```

Plot salinity

```{r}
#summarise salinity data
s_summary <- summarySE(CTD, measurevar="s_mean", groupvars=c("p","cycle_name"), na.rm=TRUE)
s_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

s_plot <- s_summary %>%
  ggplot(aes(x=s_mean, y=p, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=s_mean-sd, xmax=s_mean+sd), width=.1, position=pd) +
    geom_path() +
    geom_point(size=0.5) +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab("Salinity")+
scale_color_brewer(palette = "Dark2")
s_plot

```
#Nitrate: silicate ratio
high ratio -> 
```{r}
nutrients
nutrients <- nutrients %>%
  mutate(ni_si=NO3_uM/DRSi_uM)
nutrients

test_summary <- summarySE(nutrients, measurevar="ni_si", groupvars=c("depth","cycle_name"), na.rm=TRUE)
test_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

test_plot <- test_summary %>%
  ggplot(aes(x=ni_si, y=depth, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=ni_si-sd, xmax=ni_si+sd), width=.1, position=pd) +
    geom_path() +
    geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab(expression(paste("Nitrate:Silicate")))+
  labs(colour = "Cycle name")+
  scale_color_brewer(palette = "Dark2")
test_plot

```

```{r}
combined_figure <- plot_grid(
  temp_plot+ theme(legend.position="none"),
  s_plot+ theme(legend.position="none"),
  nitrate_plot+ theme(legend.position="none"), 
  #p_plot+ theme(legend.position="none"), 
  si_plot+ theme(legend.position="none"),
  test_plot + theme(legend.position="none"),
  labels = c("A", "B", "C", "D", "E"), 
  align = 'vh',
  hjust = -1,
  nrow = 1) 

# extract a legend that is laid out horizontally
legend_b <- get_legend(
  nitrate_plot + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
combined_figure <- plot_grid(combined_figure, legend_b, ncol = 1, rel_heights = c(1, .1))
png("../figures/combined_physical_QE.png", width = 1000, height = 500)
combined_figure
```

