---
title: "Integrated PP"
author: "Denise Ong"
date: "3/19/2021"
output: html_document
---
```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(broom)
library(ggpubr)
library(stringr)
library(RColorBrewer)
library(cowplot)
```

```{r}
npp_raw <- readxl::read_excel("data_used/TAN1810_NPP_areal.xlsx")  %>%
  select(Cycle, Station, Depth, areal_PP, mean_NPP, sd_NPP) %>%
  distinct() %>%
  mutate(cycle_name = recode(Cycle, "1" = "Subantarctic 1",
                                    "2" = "Subantarctic 2",
                                    "3" = "Subtropical 1",
                                    "4" = "Subtropical 2",
                                    "5" = "Subantarctic 3"))
```

```{r}
library(ggsci)
integrated_pp <- npp_raw %>%
  ggplot(aes(x = cycle_name, y = areal_PP)) +
  geom_boxplot(aes(fill = cycle_name))  +
  geom_point() +
  xlab("Cycle") +
  ylab("Integrated primary productivity (mgC/m2/day)") +
  scale_fill_brewer(palette = "Dark2")+
  theme_bw()+
  theme(
  axis.text.x = element_blank())

#png("../figures/C14_hot_QE.png", width = 600, height = 300)

integrated_pp
```


#Function for summarising the data
```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```

PP rate plot
```{r}
npp_plot <-npp_raw %>%
  ggplot(aes(x=mean_NPP, y= Depth, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=mean_NPP-sd_NPP, xmax=mean_NPP+sd_NPP), width=.1, position=pd) +
    geom_path() +
    geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab("Depth (m)")+
  xlab("Cycle")+
  labs(colour = "Cycle name")+
  scale_color_jco()
npp_plot
pp_summary <- summarySE(npp_raw, measurevar="mean_NPP", groupvars=c("Depth","cycle_name"), na.rm=TRUE)
pp_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

npp_plot_summary <- pp_summary %>%
  ggplot(aes(x=mean_NPP, y= Depth, colour=cycle_name)) + 
    geom_errorbar(aes(xmin=mean_NPP-sd, xmax=mean_NPP+sd), width=.1, position=pd) +
    geom_path(size=1.5) +
    geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab("Depth (m)")+
  xlab("Net Primary Productivity (mgC/m3/day)")+
  labs(colour = "Cycle name")+
  scale_color_brewer(palette = "Dark2")+
  expand_limits(y = 0)
npp_plot_summary
```

```{r}
npp_combined <- plot_grid(
  npp_plot_summary+ theme(legend.position="none"),
  integrated_pp+ theme(legend.position="none"), 
  labels = c("A", "B"), 
  align = 'vh',
  hjust = -1,
  nrow = 1) 

# extract a legend that is laid out horizontally
legend_b <- get_legend(
  npp_plot_summary + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
npp_combined <- plot_grid(npp_combined, legend_b, ncol = 1, rel_heights = c(1, .1))

npp_combined
ggsave("../figures/QE_npp combined.png")
```

