---
title: "Temperature map"
author: "Denise Ong"
date: "3/16/2021"
output: html_document
---

# Code for Figure 1
```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

Denise note:
- following this online guide  https://pjbartlein.github.io/REarthSysSci/netCDF.html
-https://rpubs.com/jonesey441/NetCDF-data 

```{r}
library(here)
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting
library(lattice)
library(RColorBrewer)
```


#Plot SST
```{r}
dname <- "sst"
nc_SST <- ncdf4::nc_open( 'data_used/AQUA_MODIS.20181101_20181130.L3m.MO.NSST.sst.4km.nc')

print(nc_SST)
```

```{r}
# get longitude and latitude
lon <- ncvar_get(nc_SST,"lon")
nlon <- dim(lon)
head(lon)

lat <- ncvar_get(nc_SST,"lat")
nlat <- dim(lat)
head(lat)
#lat <- rev(lat) #previous error - increasing X and Y values expected. Reverse the values to make increasing lat values.

print(c(nlon,nlat))
```

```{r}
# Get temperature variable
tmp_array <- ncvar_get(nc_SST,dname)
dlname <- ncatt_get(nc_SST,dname,"long_name")
dunits <- ncatt_get(nc_SST,dname,"units")
fillvalue <- ncatt_get(nc_SST,dname,"_FillValue")
dim(tmp_array) #verify the size of the array - same as before
```

```{r}
# Get global attributes
title <- ncatt_get(nc_SST,0,"title")
institution <- ncatt_get(nc_SST,0,"institution")
datasource <- ncatt_get(nc_SST,0,"source")
references <- ncatt_get(nc_SST,0,"references")
history <- ncatt_get(nc_SST,0,"history")
Conventions <- ncatt_get(nc_SST,0,"Conventions")

```

```{r}
#subset data for NZ area (coordinates lat -46 to -41, lon 172 to -176)
lon_sub <- which( nc_SST$dim$lon$vals > 171 | nc_SST$dim$lon$vals < -178)
lat_sub <- which( nc_SST$dim$lat$vals > -47 & nc_SST $dim$lat$vals < -41.3)
lon_sub <- c(which(nc_SST$dim$lon$vals > 171) , which(nc_SST$dim$lon$vals < -178) )
# replace netCDF fill values with NA's
tmp_array[tmp_array==fillvalue$value] <- NA
temp_nz <- tmp_array [lon_sub, lat_sub]
print(temp_nz)
nc_close(nc_SST)
```

```{r}
#Check current workspace
ls()
```


```{r}
#Plot all to check data. Looks ok
#image(lon,lat,tmp_array, col=rev(brewer.pal(10,"RdBu")))
```

```{r}
#Plot NZ
raster_temp_nz <- raster(temp_nz)
raster_temp_nz <-  t(raster_temp_nz)
plot(raster_temp_nz)
raster_temp_nz
```
#temperature colour plot -red and blue
```{r}
temp_nz_df <- as.data.frame(raster_temp_nz, xy = TRUE)
str(temp_nz_df)
library(paletteer)

plot_temp<- ggplot() +
  geom_raster(data = temp_nz_df , aes(x = x, y = y, fill = layer))+
  scale_fill_gradientn(colours=rev(brewer.pal(20,"RdYlBu")), breaks = c(9, 10, 11, 12, 13, 14, 15)) 
  
plot_temp
pdf("C14_map_temp.pdf", height=4, width=6) ; plot(plot_temp) ; dev.off()

```

#map with stations
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(broom)
```


## Coordinates of stations
```{r}
sampling_location <- readxl::read_excel("data_used/TAN1810_14C-Pico_25052020_QA_1.2.xlsx", sheet = "Complete data TAN1810", skip = 11) %>%
  dplyr::select (`Cycle#`, `EXP#`, `Lat_DD`, `Long_DD`) %>%   
     rename(cycle = `Cycle#`,
            exp = `EXP#`,
            lat = Lat_DD, 
            long = Long_DD) %>%
  distinct() %>%
  na.omit() %>%
  group_by(cycle, exp) %>%
  slice(1)
```

# map coordinates
```{r}
library(ggOceanMaps)

p <- basemap(limits = c(172, -179, -46, -41.5), rotate = TRUE,  lon.interval = 2, lat.interval = 1,grid.size = 0.5, bathymetry = TRUE, bathy.style = "poly_greys") + 
  geom_spatial_point(data = sampling_location, aes(x = long, y = lat))

p

 pdf("c14_map_bathy.pdf", height=5, width=7) ; plot(p) ; dev.off()
```

