---
title: "Fv/Fm"
author: "Denise Ong"
date: "3/28/2023"
output: html_document
---


#init
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(here)
source(here("init_files", "init.R")) #for libraries
source(here("init_files", "init_markdown.R")) #for markdown libraries

colours_cycle <- readxl::read_excel("init_files/colours_cycle.xlsx")
colours_cycle <- structure(colours_cycle$colour,.Names=colours_cycle$cycle)
```

```{r}
fvfm <- readxl::read_excel("data_used/TAN1810_SFChla_Nut_ETR.xlsx")  %>%
  select(CTD_type, U_Cast, Depth, Nominal_depth, Cycle, FvFm2) %>%
  distinct() %>%
  mutate(cycle_name = recode(Cycle, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) %>%
  filter(!(is.na(FvFm2))) %>%
  mutate(depth_cat = case_when (Depth == "10" ~ "SUR",
                                Depth == "12" ~ "SUR",
                                (Depth == 40 & Cycle == 1) ~ "DCM",
                                (Depth == 40 & Cycle == 2) ~ "DCM",
                                (Depth == 40 & Cycle == 3) ~ "DCM",
                                (Depth == 40 & Cycle == 4) ~ "DCM",
                                (Depth == 70 & Cycle == 5) ~ "DCM",
                                (Depth == 25 & Cycle == 3) ~ "DCM",
                                (Depth == 30 & Cycle == 4) ~ "DCM",
                               TRUE ~  as.character(cycle_name))) %>%
  filter(depth_cat %in%c ("SUR", "DCM")) %>%
  mutate(cycle_name = fct_relevel(cycle_name, "ST1", "ST2", "SA1", "SA2", "SA3"))

p <- fvfm %>%
  ggplot(aes(y = FvFm2, x = cycle_name)) +
  geom_point() +
  facet_grid(depth_cat~CTD_type)

p

summary <- fvfm %>%
  filter(CTD_type == "predawn") %>%
  group_by(cycle_name) %>%
  summarise(mean = round(mean(FvFm2),2),
            sd = round(sd(FvFm2), 2)) %>%
  unite("mean_sd", mean:sd, sep = " ± ")
summary
writexl::write_xlsx(fvfm, "fvfm_summary_2.0.xlsx")

```