---
 title: "QE_CTD and nutrients"
author: "Denise Ong"
date: "3/19/2021"
output: html_document
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               tidy = FALSE,
               fig.height=8, 
               fig.width=8,
               results = 'asis')
opts_knit$set(width=75)
```

# Load libraries

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(readxl) # Read excel file
library(lubridate) 
library("cowplot")
library("AquaEnv")
library("gsw")
library(ggsci)
library(RColorBrewer)
```

# Nutrients
# Read table, combine with C14 hot for the cycle, exp and station number.
```{r}
nutrients_raw <- readxl::read_excel("../data_used/TAN1810_nutrients.xls") %>%
  dplyr::rename(CTD = `U_Cast`,
                depth =`Depth`)

CTD_raw <- readxl::read_excel("../data_used/TK_CTD Downcasts.xlsx") %>%
  dplyr::rename(CTD = `cast`) %>%
  mutate(datetime =  dmy_hms(datetime)) %>%
  filter(!is.na(t)) %>%
  mutate(date = date(datetime)) %>%
  #mutate(time = hour(datetime)) %>%
  mutate(julian_day = julian(date, origin = date("2018-01-01"))) %>%
  select(CTD, datetime, date, julian_day) %>%
  mutate(CTD=as.character(CTD)) %>%
  distinct()

nutrients <- full_join(nutrients_raw,CTD_raw) %>%
  filter(!is.na(depth)) %>%
  filter(!is.na(julian_day)) %>%  #how to insert date for the missing dates. Corresponding CTD no. is 9167, 9171, 9169, 9168
  filter(depth<=100)
nutrients


```
```{r}
nutrients <- nutrients %>%
  mutate(cycle = NA)

nutrients$julian_day <- as.character(nutrients$julian_day)
nutrients$cycle[grep("296", nutrients$julian_day)] = "1"
nutrients$cycle[grep("297", nutrients$julian_day)] = "1"
nutrients$cycle[grep("298", nutrients$julian_day)] = "1"
nutrients$cycle[grep("299", nutrients$julian_day)] = "1"
nutrients$cycle[grep("300", nutrients$julian_day)] = "1"
nutrients$cycle[grep("301", nutrients$julian_day)] = "1"
nutrients$cycle[grep("302", nutrients$julian_day)] = "1"
nutrients$cycle[grep("305", nutrients$julian_day)] = "2"
nutrients$cycle[grep("306", nutrients$julian_day)] = "2"
nutrients$cycle[grep("307", nutrients$julian_day)] = "2"
nutrients$cycle[grep("308", nutrients$julian_day)] = "2"
nutrients$cycle[grep("309", nutrients$julian_day)] = "2"
nutrients$cycle[grep("311", nutrients$julian_day)] = "3"
nutrients$cycle[grep("312", nutrients$julian_day)] = "3"
nutrients$cycle[grep("313", nutrients$julian_day)] = "3"
nutrients$cycle[grep("315", nutrients$julian_day)] = "4"
nutrients$cycle[grep("316", nutrients$julian_day)] = "4"
nutrients$cycle[grep("317", nutrients$julian_day)] = "4"
nutrients$cycle[grep("319", nutrients$julian_day)] = "5"
nutrients$cycle[grep("320", nutrients$julian_day)] = "5"

nutrients <- nutrients %>%
  filter(!is.na(cycle)) %>%
  mutate(cycle_name = recode(cycle, "1" = "Subantarctic 1",
                                    "2" = "Subantarctic",
                                    "3" = "Subtropical",
                                    "4" = "Subtropical 2",
                                    "5" = "Subantarctic 3")) %>%
  filter(CTD %in% c("9125","9142"))

nutrients$cycle_name<-factor(nutrients$cycle_name, levels = c("Subtropical", "Subantarctic"))

check <- nutrients  %>% 
  select(CTD, date, cycle) %>%
  distinct()
check
nutrients
```


Plot nitrate

```{r}
nitrate_plot <- nutrients %>%
  ggplot(aes(x=NO3_uM, y=depth, colour=cycle_name)) + 
  geom_path() +
  geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab(expression(paste("Nitrate (",mu,"M)")))+
  labs(colour = "Cycle")+
  scale_color_brewer(palette = "Dark2")+
  theme(legend.title =element_text(size=12,face="bold"),
        legend.text = element_text(size=12))+
  scale_colour_manual(values = c("#FF0000", "#0066CC"))+
  expand_limits(x=0, y=0)+
   theme(axis.title=element_text(size= 20),
        axis.text = element_text(size = 15),
        legend.title =element_text(size=20,face="bold"),
        legend.text = element_text(size=20))
 
nitrate_plot

```
Plot phosphate

```{r}
phosphate_plot <- nutrients %>%
  ggplot(aes(x=DRP_uM, y=depth, colour=cycle_name)) + 
  geom_path() +
  geom_point() +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL)+
  xlab(expression(paste("Phosphate (",mu,"M)")))+
  labs(colour = "Cycle")+
  scale_color_brewer(palette = "Dark2")+
  theme(legend.title =element_text(size=12,face="bold"),
        legend.text = element_text(size=12))+
  scale_colour_manual(values = c("#FF0000", "#0066CC"))+
  expand_limits(x=0, y=0)+
  theme(axis.title=element_text(size= 20),
        axis.text = element_text(size = 15),
        legend.title =element_text(size=20,face="bold"),
        legend.text = element_text(size=20))
 
phosphate_plot

```

# CTD
# Read table.
```{r}
CTD_raw <- readxl::read_excel("../data_used/TK_CTD Downcasts.xlsx") %>%
  dplyr::rename(CTD = `cast`) %>%
  mutate(datetime =  dmy_hms(datetime)) %>%
  filter(!is.na(t)) %>%
  mutate(date = date(datetime)) %>%
  mutate(time = hour(datetime)) %>%
  mutate(julian_day = julian(date, origin = date("2018-01-01"))) %>%
  filter(time %in% (9:12) ) %>%
  mutate(t_mean = (t+t2)/2) %>%
  mutate(s_mean = (s+s2)/2) %>%
  mutate(os_mean = (os+os2)/2) %>%
  select(-t, -t2, -s, -s2, -os, -os2) %>%
  filter(p <= 100) %>%
  filter(julian_day %in% c("305", "311"))
CTD_raw
```

```{r}
CTD <- CTD_raw %>%
  mutate(cycle = NA)

CTD$julian_day <- as.character(CTD$julian_day)
CTD$cycle[grep("297", CTD$julian_day)] = "1"
CTD$cycle[grep("298", CTD$julian_day)] = "1"
CTD$cycle[grep("299", CTD$julian_day)] = "1"
CTD$cycle[grep("300", CTD$julian_day)] = "1"
CTD$cycle[grep("301", CTD$julian_day)] = "1"
CTD$cycle[grep("302", CTD$julian_day)] = "1"
CTD$cycle[grep("305", CTD$julian_day)] = "2"
CTD$cycle[grep("306", CTD$julian_day)] = "2"
CTD$cycle[grep("307", CTD$julian_day)] = "2"
CTD$cycle[grep("308", CTD$julian_day)] = "2"
CTD$cycle[grep("309", CTD$julian_day)] = "2"
CTD$cycle[grep("311", CTD$julian_day)] = "3"
CTD$cycle[grep("312", CTD$julian_day)] = "3"
CTD$cycle[grep("313", CTD$julian_day)] = "3"
CTD$cycle[grep("315", CTD$julian_day)] = "4"
CTD$cycle[grep("316", CTD$julian_day)] = "4"
CTD$cycle[grep("317", CTD$julian_day)] = "4"
CTD$cycle[grep("319", CTD$julian_day)] = "5"
CTD$cycle[grep("320", CTD$julian_day)] = "5"

CTD <- CTD %>% mutate(cycle_name = recode(cycle, "1" = "Subantarctic 1",
                                    "2" = "SA",
                                    "3" = "ST",
                                    "4" = "Subtropical 2",
                                    "5" = "Subantarctic 3")) 
#CTD$cycle_name <- factor(CTD$cycle_name,levels = c("Subtropical 1", "Subtropical 2", "Subantarctic 1", "Subantarctic 2", "Subantarctic 3")) 

CTD <- CTD %>%
    filter(!is.na(cycle)) #remove rows without cycle number
CTD$cycle_name<- factor(CTD$cycle_name,levels = c("ST","SA"))
CTD
```
Plot temperature

```{r}

temp_plot <- CTD %>%
  ggplot(aes(x=t_mean, y=p, colour=cycle_name)) + 
    geom_path() +
    geom_point(size=0.5) +
  scale_y_reverse()+
  theme_bw() +
  ylab("Depth (m)")+
  xlab(expression(paste("Temperature (",degree,"C)")))+
  labs(colour = "Cycle")+
 scale_colour_manual(values = c("#FF0000", "#0066CC"))+
   theme(axis.title=element_text(size= 20),
        axis.text = element_text(size = 15),
        legend.title =element_text(size=20,face="bold"),
        legend.text = element_text(size=15))
 
temp_plot

```

Plot salinity

```{r}

salinity_plot <- CTD %>%
  ggplot(aes(x=s_mean, y=p, colour=cycle_name)) + 
    geom_path() +
    geom_point(size=0.5) +
  scale_y_reverse()+
  theme_bw() +
  ylab(NULL) +
  xlab("Salinity")+
  labs(colour = "Cycle")+
 scale_colour_manual(values = c("#FF0000", "#0066CC"))+
  theme(axis.title=element_text(size= 20),
        axis.text = element_text(size =15),
        legend.title =element_text(size=20,face="bold"),
        legend.text = element_text(size=20))
 
salinity_plot

```


```{r}
prow <- plot_grid(
  temp_plot + theme(legend.position="none"),
  salinity_plot + theme(legend.position="none"),
  nitrate_plot + theme(legend.position="none"),
  phosphate_plot + theme(legend.position="none"),
  align = 'vh',
  labels = c("A", "B", "C", "D"),
  hjust = -1,
  nrow = 1,
 label_size = 20
)
prow

# extract the legend from one of the plots
legend <- get_legend(
  # create some space to the left of the legend
  temp_plot+ theme(legend.box.margin = margin(0, 0, 0, 12))
)

# add the legend to the row we made earlier. Give it one-third of 
# the width of one plot (via rel_widths).
QE_temp_nitrate<-plot_grid(prow, legend, rel_widths = c(3, .4))

png("../figures/QE_temp_nitrate.png", , width = 1000, height = 250)
#png("../figures/combined_physical_QE.png", width = 1000, height = 500)
QE_temp_nitrate

```

```{r}

prow <- plot_grid(
 temp_plot + theme(legend.position="none"),
  nitrate_plot + theme(legend.position="none"),
  align = 'vh',
  labels = c("A", "B"),
  hjust = -1,
  nrow = 1,
 label_size = 30
)
prow

# extract the legend from one of the plots
legend <- get_legend(
  # create some space to the left of the legend
  temp_plot+ theme(legend.box.margin = margin(0, 0, 0, 12))
)

# add the legend to the row we made earlier. Give it one-third of 
# the width of one plot (via rel_widths).
QE_temp_nitrate<-plot_grid(prow, legend, rel_widths = c(3, .4))

png("../figures/QE_temp_nitrate.png", width = 1000, height = 250)
#png("../figures/combined_physical_QE.png")
QE_temp_nitrate
```

