---
title: "Temperature and chlorophyll map"
author: "Denise Ong"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

Denise note:
- following this online guide  https://pjbartlein.github.io/REarthSysSci/netCDF.html
-https://rpubs.com/jonesey441/NetCDF-data 

```{r}
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting
library(lattice)
library(RColorBrewer)
```

#Plot SST
```{r}
dname <- "sst"
nc_SST <- nc_open( '../data_used/AQUA_MODIS.20181101_20181130.L3m.MO.NSST.sst.4km.nc')
#print(nc_SST)
```

```{r}
# get longitude and latitude
lon <- ncvar_get(nc_SST,"lon")
nlon <- dim(lon)
head(lon)

lat <- ncvar_get(nc_SST,"lat")
nlat <- dim(lat)
head(lat)
#lat <- rev(lat) #previous error - increasing X and Y values expected. Reverse the values to make increasing lat values.

print(c(nlon,nlat))
```

```{r}
# Get temperature variable
tmp_array <- ncvar_get(nc_SST,dname)
dlname <- ncatt_get(nc_SST,dname,"long_name")
dunits <- ncatt_get(nc_SST,dname,"units")
fillvalue <- ncatt_get(nc_SST,dname,"_FillValue")
dim(tmp_array) #verify the size of the array - same as before
```

```{r}
# Get global attributes
title <- ncatt_get(nc_SST,0,"title")
institution <- ncatt_get(nc_SST,0,"institution")
datasource <- ncatt_get(nc_SST,0,"source")
references <- ncatt_get(nc_SST,0,"references")
history <- ncatt_get(nc_SST,0,"history")
Conventions <- ncatt_get(nc_SST,0,"Conventions")

```

```{r}
#subset data for NZ area (coordinates lat -46 to -41, lon 172 to -176)
lon_sub <- which( nc_SST$dim$lon$vals > 172 | nc_SST$dim$lon$vals < -176)
lat_sub <- which( nc_SST$dim$lat$vals > -46 & nc_SST $dim$lat$vals < -41)
lon_sub <- c(which(nc_SST$dim$lon$vals > 172) , which(nc_SST$dim$lon$vals < -176) )
# replace netCDF fill values with NA's
tmp_array[tmp_array==fillvalue$value] <- NA
temp_nz <- tmp_array [lon_sub, lat_sub]
nc_close(nc_SST)
```

```{r}
#Check current workspace
ls()
```


```{r}
#Plot all to check data. Looks ok
#image(lon,lat,tmp_array, col=rev(brewer.pal(10,"RdBu")))
```

```{r}
#Plot NZ
raster_temp_nz <- raster(temp_nz)
raster_temp_nz <-  t(raster_temp_nz)
plot(raster_temp_nz)
raster_temp_nz
```

```{r}
temp_nz_df <- as.data.frame(raster_temp_nz, xy = TRUE)
str(temp_nz_df)

#error here. The axis values are not coordinates (lat -46 to -41, lon 172 to -176). I think the way would be to create a new create a column with the coordinates, but because of the way the data is formed I'm not sure how to do.
plot_temp<- ggplot() +
    geom_raster(data = temp_nz_df , aes(x = x, y = y, fill = layer)) +
    scale_fill_viridis_c() +
    coord_quickmap()+
    theme(aspect.ratio = 3/4)
plot_temp

```

# Plot Chlorophyll data
```{r}
nc_chl <- nc_open( '../data_used/A20183052018334.L3m_MO_CHL_chlor_a_4km.nc')
#print(nc_chl)

varname<-names(nc_chl$var)
varname
```

## Get coordinate variables
```{r}
# get longitude and latitude
lon_chl <- ncvar_get(nc_chl,"lon")
nlon <- dim(lon_chl)
head(lon_chl)
lon_chl <- as.numeric(lon_chl)

lat_chl <- ncvar_get(nc_chl,"lat")
nlat <- dim(lat_chl)
head(lat_chl)
lat_chl <- as.numeric(lat_chl)
lat_chl <- rev(lat_chl)
#lat <- rev(lat) #previous error - increasing X and Y values expected. Reverse the values to make increasing lat values.

print(c(nlon,nlat))
```

```{r}
# Get chlorophyll a variable
chl_array <- ncvar_get(nc_chl,"chlor_a")
dlname <- ncatt_get(nc_chl,"chlor_a","long_name")
dunits <- ncatt_get(nc_chl,"chlor_a","units")
fillvalue <- ncatt_get(nc_chl,"chlor_a","_FillValue")
dim(chl_array) #verify the size of the array - same as lat lon
```

```{r}
#subset data for NZ area (coordinates lat -47 to -41, long 172 to -176)
#subset is not working, gives empty integers. Why?
lon_sub_chl <- which( nc_chl$dim$lon_chl$vals > 172 | nc_chl$dim$lon_chl$vals < -176)
lat_sub_chl <- which( nc_chl$dim$lat_chl$vals > -47 & nc_chl $dim$lat$vals < -41)
lon_sub_chl <- c(which(nc_chl$dim$lon_chl$vals > 172) , which(nc_chl$dim$lon_chl$vals < -176) )
# replace netCDF fill values with NA's
chl_array[chl_array==fillvalue$value] <- NA
chl_nz <- chl_array [lon_sub_chl, lat_sub_chl]
nc_close(nc_chl)
```

```{r}
#Plot all to check data. Looks ok
image(lon_chl,lat_chl,chl_array, col=rev(brewer.pal(10,"RdBu")))
```

```{r}
#Plot NZ
raster_chl_nz <- raster(chl_nz)
raster_chl_nz <-  t(raster_chl_nz)
plot(raster_chl_nz)
```