---
title: "Studies comparison"
author: "Denise Ong"
date: "4/15/2021"
output: html_document
---
```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(broom)
library(ggpubr)
library(stringr)
library(RColorBrewer)
library(cowplot)
```

#Colours for cycle
```{r}
colours_water <- readxl::read_excel("colours_cycle.xlsx", sheet =  "Sheet3")
colours_water <- structure(colours_water$colour,.Names=colours_water$water)
```

```{r}

studies <- readxl::read_excel("../data_used/C14_studies.xlsx", sheet = "Sheet4")  #updated one study

studies$Study <- factor(studies$Study, levels = c("Li 1994", "Jardilier 2010", "Grob 2011", "Hartman 2014", "Rii 2016",  "Duerschlag 2021","Irion 2021", "This study"))
studies$Group<-factor(studies$Group, levels = c("Synechococcus", "Picoeukaryotes", "Nanoeukaryotes"))
studies$cat<-factor(studies$cat, levels = c("tropical", "ST", "SA", "antarctic"))

#break up to two graphs, less than 30, more than 30 - ignore 
blank <- studies %>%
  dplyr::select(Study, Group, cat)

lower <- studies %>%
  filter(Upper <30) %>%
  full_join(blank)

upper <- studies %>%
  filter(Upper >30) %>%
  full_join(blank)

p1 <- lower %>% 
  ggplot(aes(Study, ymin = Lower, ymax = Upper, color = cat)) +
  geom_linerange(position = position_dodge(width = 1), size = 5) +
  facet_grid(.~ Group, scales = "free", space = "free") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab(expression(Primary~Production~(fgC~cell^-1~day^-1))) +
  theme(strip.text.x = element_blank(),
        panel.spacing.x = unit(0,"line")) +
  scale_color_manual(values = colours_water, name = "Water mass") +
  theme(legend.position="none")
p1

p2 <- upper %>% 
  ggplot(aes(Study, ymin = Lower, ymax = Upper, color = cat)) +
  geom_linerange(position = position_dodge(width = 1), size = 5) +
  facet_grid(.~ Group, scales = "free", space = "free")+
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(),
        panel.spacing.x = unit(0,"line")) + #remove x axis ticks
  xlab(NULL) +
  ylab(NULL) +
  scale_color_manual(values = colours_water, name = "Water_mass") + theme(legend.position="none")
p2

library(cowplot)

prow <- plot_grid(
  p2  + theme(legend.position="none"),
  p1 + theme(legend.position="none"),
  align = 'v',
  axis = "l",
  hjust = -1,
  nrow = ,
  rel_heights = c(1, 2)
)

prow
pdf("figures/GRC/pp_rates_studies_2.pdf", height=4, width=6) ; plot(prow) ; dev.off()

p <- studies %>% 
  ggplot(aes(Study, ymin = Lower, ymax = Upper, color = cat)) +
  geom_linerange(position = position_dodge(width = 1), size = 5) +
  facet_grid(.~ Group, scales = "free", space = "free") +
   scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l", 
                      short = unit(0.07, "cm"),
                      mid = unit(0.15, "cm"),
                      long = unit(0.2, "cm"),
                      size = 0.3) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab(expression(Primary~Production~(fgC~cell^-1~day^-1))) +
  theme(strip.text.x = element_blank(),
        panel.spacing.x = unit(0,"line")) +
  scale_color_manual(values = colours_water, name = "Water mass") +
  theme(legend.position="bottom")
p
pdf("figures/GRC/pp_rates_studies_3.pdf", height=4, width=6) ; plot(p) ; dev.off()

```


```{r, eval=FALSE}
#ignore this
studies <- readxl::read_excel("../data_used/C14_studies.xlsx", sheet = "Sheet2")  

studies$Study <- factor(studies$Study, levels = c("Li (1994)", "Jardilier et al. (2010)", "Grob et al. (2011)", "Rii et al. (2016)", "Irion et al. (2021)", "Duerschlag et al. (2021)", "This study (ST)", "This study (SA)"))
studies$Group<-factor(studies$Group, levels = c("Synechococcus", "Picoeukaryotes", "Nanoeukaryotes"))

studies_plot<- studies %>%
  ggplot(aes(x=Study, y=Rate)) +
  geom_boxplot()+
  facet_grid(.~ Group, scales = "free", space = "free")+
  scale_y_continuous(trans='log10') +
  annotation_logticks(sides = "l") +
  theme_bw()+
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(axis.text.x = element_text(size = 7, angle = 90, hjust=1))+
  ylab("Primary Production rate\n(fgC/cell/h)")

studies_plot

pdf("figures/ACOP_figures/pp_rates_studies.pdf", height=4, width=6) ; plot(studies_plot) ; dev.off()

```
