---
title: "Supp tables"
author: "Denise Ong"
date: "3/17/2023"
output: html_document
---
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(broom)
```

```{r}
C14_DPM <- readxl::read_excel("data_used/TAN1810_14C-Pico_25052020_QA_1.2.xlsx", sheet = "Complete data TAN1810", skip = 11) %>%
  dplyr::select (date, Lat_DD, Long_DD, `Cycle#`, `EXP#`, STN, DEPTH, SAMPLE, `Vial code             (i - initials, A to C - light incubation, D - dark)`, `sorting population`, `Cells sorted`, DPM1, DIC, `SA_dpm_mL`) %>%   
     rename(lat = Lat_DD,
            long = Long_DD,
            cycle = `Cycle#`,
            exp = `EXP#`,
            station = STN,
            depth_m = DEPTH,
            depth = SAMPLE, 
            vial = `Vial code             (i - initials, A to C - light incubation, D - dark)`, 
            population = `sorting population`, 
            cells_sorted = `Cells sorted`, 
            dpm = DPM1,
            SA = `SA_dpm_mL`) %>%
  select(date:cells_sorted) %>%
  mutate(cycle_name = recode(cycle, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) %>%
  select(-cycle) %>%
  select(date, lat, long, station, cycle_name, exp, depth_m, depth, vial, population, cells_sorted) 
    #filter(population != "Nano") %>%
   # filter(population != "Nano" | (population == "Nano" & exp == 8 & sample == "SUR" & vial == "B") | (population == "Nano" & exp == 8 & sample == "SUR" & vial == "D")) %>% # cells sorted for both 1000 and 2000
    # filter(!(exp == 3 & sample == "SUR" & vial == "A" & population == "Pico")) %>% # Decreasing LM value.
    # filter(!(exp == 2 & sample == "DCM" & vial == "A" & population == "Pico")) %>% # DPM is lower than the average dark vial. Remove
    #  group_by(cycle, exp, sample, vial, population, cells_sorted) %>% 
    #  summarize(cells_sorted = mean(cells_sorted),
    #            dpm= mean(dpm),
    #            DIC = mean(DIC),
    #            SA = mean(SA)) %>%
    # ungroup()

C14_DPM

writexl::write_xlsx(C14_DPM, "supp table_rates cells sorted.xlsx")
```

```{r}
table <- read.csv("data_used/supp table_DNA cells sorted.txt", sep = "\t")
table <- readxl::read_excel("data_used/C14_studies.xlsx", sheet = "for_R") %>%
  unite("rate", Lower:Upper, sep=" ± ", remove = TRUE)

table <- readxl::read_excel("growth rate stats.xlsx")

library(xtable)
print(xtable(table),
      comment = FALSE,
      include.rownames=FALSE,
      digits=-3)
```

#Pigment
```{r}
pigment <- readxl::read_excel("data_used/TAN1810_Decima pigment_pangea.xlsx") %>%
  select(Cy, Perid:'Chl b') %>%
  mutate(cycle_name = recode(Cy, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) %>%
  select(-Cy) %>%
  pivot_longer(Perid:'Chl b', names_to = "pigment", values_to = "prop") %>%
  mutate(cycle_name = fct_relevel(cycle_name, "ST1", "ST2", "SA1", "SA2", "SA3")) %>%
  mutate(group = recode(pigment, "But-fuco" = "Pelagophyceae",
                         "Hex=fuco"= "Prymnesiophyceae",
                         "Allo" ="Cryptophyceae",
                         "Chl b" ="Prasinophyceae",
                         "Pras"= "Prasinophyceae",
                         "Fuco" ="Diatoms", 
                         "Perid"= "Dinophyceae",
                         "Zea"= "Synechococcus",
                         "DV chl a"= "Prochloroccus"))
library(paletteer)
p <- pigment %>%
  ggplot(aes(x=cycle_name, y=prop, fill =group)) +
  geom_bar(stat="identity", position = "fill") +
  scale_fill_paletteer_d("RColorBrewer::Accent") +
  xlab(NULL) +
  ylab("Proportion of pigment (%)") +
  theme(legend.position="top") 
p
```

```{r}
fvfm <- readxl::read_excel("data_used/TAN1810_Decima fvfm_pangea.xlsx") %>%
  select(Cy, Depth, depth_cat, fvfm) %>%
  mutate(cycle_name = recode(Cy, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) %>%
  select(-Cy) %>%
  mutate(cycle_name = fct_relevel(cycle_name, "ST1", "ST2", "SA1", "SA2", "SA3")) %>%
  filter(depth_cat %in%c ("SUR", "DCM")) %>%
  group_by(cycle_name) %>%
  summarise(mean = round(mean(fvfm),3),
            sd = round(sd(fvfm), 3)) %>%
  unite("mean_sd", mean:sd, sep = " ± ")

writexl::write_xlsx(fvfm, "fvfm_summary.xlsx")

# %>%
#   pivot_wider(names_from = "cycle_name", values_from = "mean_sd")
```

