---
title: "18S heatmap"
author: "Denise Ong"
date: "10/28/2022"
output: html_document
---

# Initialize
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(here)
source(here("phyloseq", "init_files", "init.R")) #for libraries
source(here("phyloseq", "init_files", "init_markdown.R")) #for markdown libraries
source(here("phyloseq", "init_files", "define_functions.R")) #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps
source(here("phyloseq", "trophic_mode", "trophic_function.R"))  #function to assign trophic level for phyloseq objects
source(here("phyloseq", "init_files", "colours_18sv4.R")) # predetermined colours
#source(here("phyloseq", "init_files", "colours_random.R")) #random colours
source(here("phyloseq", "init_files", "top_taxa_func.R")) #Function to select top taxa
```

#read data
```{r}
source(here("phyloseq", "init_files", "read_18s_filt_sort.R"))

ps_filt_sort <- phyloseq_assign_trophic(ps_filt_sort) %>%
    subset_taxa(trophic_mode_2 != "heterotrophic") #remove heterotrophs
# Do normalizations and transformation
ps_filt_sort <- phyloseq_normalize_median(ps_filt_sort)
long_filt_sort <- phyloseq_transform_to_long(ps_filt_sort)  %>%
  mutate(cycle_name_2 = fct_relevel(cycle_name_2, "ST1", "ST2", "SA1", "SA2", "SA3")) %>%
  mutate(sample = fct_relevel(sample, "SUR", "DCM")) %>%
    filter(!(file_code %in% c("pico-01-30", "pico-15", "nano-12", "CTD-18S-neg"))) %>% #filter problem samples
  select(asv_code:sample_name, sample_type, sample, cycle_name_2, depth_category, cycle_station)

# convert n_reads to percent
reads_to_pct <- function(df) {
df <- df %>%
    group_by(file_code) %>% 
    mutate(pct_reads = n_reads / sum(n_reads) * 100)
}



#ong_filt_sort <- long_filt_sort %>%
#    group_by(sample_name) %>% 
#    mutate(pct_reads = n_reads / sum(n_reads) * 100) %>%
#    select(-n_reads)
```

# create a new dataframe only with overlapping ASVs for filt.
```{r}
long_pico <- long_filt_sort %>%
    filter(sample_type == "Pico")
long_nano <- long_filt_sort %>%
    filter(sample_type == "Nano")

long_asvhash <- long_filt_sort %>%
    filter(sample_type %in% c("Pico", "Nano")) %>%
    ungroup() %>%
    select(asv_code) %>%
    distinct()

long_filt<- long_filt_sort %>%
    filter(sample_type == "filt")

long_filt_overlap <- inner_join(long_filt, long_asvhash, by = "asv_code") %>%
    distinct()

long_filt_sort_overlap <- full_join(long_filt_overlap, long_pico) %>%
  full_join(long_nano) %>%
    distinct()

long_nano_asvhash <- long_nano %>%
  ungroup() %>%
  select(asv_code)
long_filt_nano <- inner_join(long_filt, long_nano_asvhash, by = "asv_code") %>%
  distinct()
long_filt_nano_overlap <- full_join(long_filt_nano, long_nano) %>%
  distinct()

long_pico_asvhash <- long_pico %>%
  ungroup() %>%
  select(asv_code)
long_filt_pico <- inner_join(long_filt, long_pico_asvhash, by = "asv_code") %>%
  distinct()

long_filt_pico_overlap <- full_join(long_filt_pico, long_pico) %>%
  distinct()
```
```{r}
library(here)
library(vegan)
source(here("phyloseq", "init_files", "init.R")) #for libraries
source(here("phyloseq", "init_files", "init_markdown.R")) #for markdown libraries
source(here("phyloseq", "init_files", "define_functions.R")) #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps 

#Colours for cycle
colours_cycle <- readxl::read_excel(here("phyloseq", "init_files", "colours_cycle copy.xlsx"))
colours_cycle <- structure(colours_cycle$colour,.Names=colours_cycle$cycle)
```


#overall
```{r}
p <- long_filt_sort_overlap %>%
    ps_top_asv(15) %>% #select top 15 asvs per sample
  reads_to_pct() %>%
  group_by(cycle_name_2, sample_type, class, order) %>%
  summarise(pct_reads = mean(pct_reads)) %>%
   # filter(pct_reads > 5) %>%
    #unite("cycle_depth", cycle_name_2, sample, sep = "_" ) %>%
    ggplot(aes(x=sample_type, y = order, fill =pct_reads)) +
    geom_tile() +
    scale_fill_binned(type = "viridis", trans = "log", breaks = c(5, 10, 15, 20, 25, 50)) +
    theme(text=element_text(size=10),
              axis.text.x = element_text(angle = 90, hjust = 1),
              panel.spacing.x = unit(0,"lines"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              strip.background = element_blank(),
              strip.text.y.right = element_text(angle = 0),
              panel.border = element_rect(colour = "black", fill = NA)) +
    facet_grid(class~cycle_name_2, scales = "free", space = "free")
p
```

```{r}
p <- long_filt_pico_overlap %>%
    #filter(sample_type %in% c("Pico", "Nano")) %>%
    ps_top_asv(15) %>% #select top 15 asvs per sample
  reads_to_pct() %>%
   # filter(pct_reads > 5) %>%
    #unite("cycle_depth", cycle_name_2, sample, sep = "_" ) %>%
    ggplot(aes(x=sample_type, y = asv_code, fill =pct_reads)) +
    geom_tile() +
    scale_fill_binned(type = "viridis", trans = "log", breaks = c(2, 5, 10, 15, 20, 25, 50)) +
    theme(text=element_text(size=10),
              axis.text.x = element_text(angle = 90, hjust = 1),
          axis.text.y=element_blank(),
          panel.spacing.x = unit(0,"lines"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              strip.background = element_blank(),
              strip.text.y.right = element_text(angle = 0),
              panel.border = element_rect(colour = "black", fill = NA)) +
    facet_grid(class~cycle_name_2, scales = "free", space = "free")
p
```