---
title: "QE chlorophyll and primary production figure"
author: "Denise Ong"
date: "3/31/2021"
output: html_document
---

```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(broom)
library(ggpubr)
library(stringr)
library(RColorBrewer)
library(cowplot)
```


#NPP figure
```{r}
npp_raw <- readxl::read_excel("data_used/TAN1810_NPP_areal.xlsx")  %>%
  select(Cycle, Station, Depth, areal_PP, mean_NPP, sd_NPP) %>%
  distinct %>%
  mutate(cycle_name = recode(Cycle, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) 
```



#chl figure
```{r}
chl_raw <- readxl::read_excel("data_used/TAN1810_SFChla.xls") %>%
  select(U_Cast, Depth,  Chla_0.2:Chla_20_pct)%>%
  filter(!is.na(U_Cast))
chl_raw$U_Cast<-as.character(chl_raw$U_Cast)
#for cycle number
NPP_raw <- readxl::read_excel("data_used/TAN1810_NPP_areal.xlsx") %>%
  select(Cycle, Station, U_Cast) %>%
  distinct()

chl_raw <- left_join(chl_raw,NPP_raw)
chl_raw

check <- chl_raw %>%
  select(U_Cast, Cycle) %>%
  distinct()
check
# Many ctd cast without cycle number,  cannot find in voyage report. To check

chl_subset <- chl_raw %>%
  filter(!is.na(Cycle))%>%
  mutate(cycle_name = recode(Cycle, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) %>%
  mutate(cycle_name = fct_relevel(cycle_name, 
            "ST1", "ST2", "SA1", 
            "SA2", "SA3"))%>%
  filter(!is.na(Chla_2)) %>%
  filter(!is.na(Chla_20))
chl_subset
```


#Function for summarising the data
```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```



```{r}

chl_summary <- summarySE(chl_subset, measurevar="SumSFChla", groupvars=c("cycle_name"), na.rm=TRUE)
chl_summary

detach(package:plyr)
frac_chl_summary <- chl_subset %>%
  dplyr::group_by(cycle_name) %>%
  summarise("Pico: 0.2-2 um" = mean(Chla_0.2),
            "Nano: 2-20 um" = mean(Chla_2),
            "Micro: >20 um" = mean(Chla_20)) %>%
  pivot_longer("Pico: 0.2-2 um":"Micro: >20 um",
               names_to = "fraction",
               values_to = "chl")
frac_chl_summary

pd <- position_dodge(0.1) # move them .05 to the left and right

chl_summary_plot <- ggplot()+
  geom_errorbar(data=chl_summary, aes(ymin=SumSFChla-sd, ymax=SumSFChla+sd, x= cycle_name), width=.1, position=pd) +
  geom_bar(data = frac_chl_summary, aes(x=cycle_name, y= chl, fill=factor(fraction, levels = c("Micro: >20 um", "Nano: 2-20 um", "Pico: 0.2-2 um"))), stat="identity")+
  theme_bw() +
  scale_fill_brewer(palette = "Dark2")+
  ylab(expression(TChl~a~(mg~m^-3)))+
  xlab("Cycle")+
  labs(fill="Size fraction")+
  theme(axis.title=element_text(size= 20),
        axis.text = element_text(size = 15),
        legend.title =element_text(size=20,face="bold"),
        legend.text = element_text(size=20))

chl_summary_plot


chl_presentation_plot <- chl_subset%>%
  ggplot(aes(x=cycle_name, y= SumSFChla))+
  geom_boxplot(aes (fill=cycle_name))+
  geom_point ()+
  theme_bw() +
  scale_fill_manual(values = c("#FF0000", "#CC0033", "#99CCFF","#3399FF", "#0066CC"))+
  ylab(expression(Total~chlorophyll~(mg~m^-3)))+
  xlab("Location") +
  theme(legend.position="none")+
  theme(axis.title=element_text(size= 20),
        axis.text = element_text(size = 15),
        axis.text.x = element_text(size = 20))

chl_presentation_plot
```


#chl integrated figure
```{r}
chl_raw_integrated <- readxl::read_excel("data_used/TAN1810_SFChla.xls", sheet = "Sheet2") %>%
  select(U_Cast, areal_chl)%>%
  filter(!is.na(U_Cast))%>%
  filter(!is.na(areal_chl))
chl_raw_integrated$U_Cast<-as.character(chl_raw_integrated$U_Cast)
#for cycle number
NPP_raw <- readxl::read_excel("data_used/TAN1810_NPP_areal.xlsx") %>%
  select(Cycle, Station, U_Cast) %>%
  distinct()

chl_raw_integrated <- left_join(chl_raw_integrated,NPP_raw)
chl_raw_integrated

check_2 <- chl_raw_integrated %>%
  select(U_Cast, Cycle) %>%
  distinct()
check_2
# Many ctd cast without cycle number,  cannot find in voyage report. To check

chl_subset_integrated <- chl_raw_integrated %>%
  filter(!is.na(Cycle))%>%
  mutate(cycle_name = recode(Cycle, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3")) %>%
  mutate(cycle_name = fct_relevel(cycle_name, 
            "ST1", "ST2", "SA1", 
            "SA2", "SA3"))
chl_subset_integrated
```

```{r}
chl_int_plot <- chl_subset_integrated%>%
  ggplot(aes(x=cycle_name, y= areal_chl))+
  geom_boxplot(aes (fill=cycle_name))+
  geom_point ()+
  theme_bw() +
  scale_fill_manual(values = c("#FF0000", "#CC0033", "#99CCFF","#3399FF", "#0066CC"))+
  ylab(expression(Total~chlorophyll~(mg~m^-2)))+
  xlab("Location") +
  theme(legend.position="none")+
  theme(axis.title=element_text(size= 20),
        axis.text = element_text(size = 15),
        axis.text.x = element_text(size = 20))+
  expand_limits(y=0)

chl_int_plot
```


```{r}

library(cowplot)

presentation_plot <- plot_grid(
  chl_int_plot,
  integrated_pp,
  align = 'vh',
  labels = c("A", "B"),
  hjust = -1,
  nrow = 1,
  label_size = 20
)


png("../figures/QE_chl_npp_edit.png", width = 1000, height = 500)
presentation_plot

```

```{r}
library(cowplot)
# arrange the three plots in a single row, leaving space between plot B and C
prow <- plot_grid(
  chl_summary_plot+ theme(legend.position="none"),
  NULL,
  integrated_pp,
  align = 'vh',
  labels = c("A","", "B"),
  hjust = -1,
  nrow = 1,
  rel_widths = c(1,.3, 1),
  label_size = 20
)
legend <- get_legend(
  # create some space to the left of the legend
  chl_summary_plot + theme(legend.box.margin = margin(0, 0, 0, 12))
)
# now add in the legend
chl_npp_combined <- prow + draw_grob(legend, 0, .3/3.3, 1)

png("../figures/QE_chl_npp.png", width = 1000, height = 500)
chl_npp_combined

```