library(stringr)
library(ggplot2)
theme_set(theme_classic())
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(maps)
library(glue)
library(cowplot)
library(phyloseq)
library(forcats)
library(paletteer)
library(peRReo)
library(broom)
library(RColorBrewer)
library(lme4)
library(readxl) # Read excel file
library(lubridate) 
library(patchwork)
library(car)

#Colours
colours_cycle <- readxl::read_excel("init_files/colours_cycle.xlsx")
colours_cycle <- structure(colours_cycle$colour,.Names=colours_cycle$cycle)
