---
title: "Supp figures_incubation vials"
author: "Denise Ong"
date: "3/18/2023"
output: html_document
---

Supplementary figures S10, S11, S12 for sorted samples Syn, Pico, Nano. Vials  A-D, i.
# Initialize
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(here)
source(here("3_Phyloseq output and figures", "init_files", "init.R")) #for libraries
source(here("3_Phyloseq output and figures", "init_files", "init_markdown.R")) #for markdown libraries
source(here("3_Phyloseq output and figures", "init_files", "define_functions.R")) #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps 
source(here("3_Phyloseq output and figures", "init_files", "colours_petb.R")) #colours
source(here("3_Phyloseq output and figures", "init_files", "colours_18sv4.R")) # predetermined colours
```

# Read data
```{r}
source(here("3_Phyloseq output and figures", "init_files", "read_petb_2.0.R"))
```

# Supplementary figure S10 - sorted Syn, compare initials, light, dark
```{r}
long <- long_sorted %>%
  dplyr::rename(station = STN,
                exp = `EXP.`,
                depth_cat = SAMPLE) %>%
  mutate(cycle_name = recode(Cycle., "1" = "SA-Sc",
                                    "2" = "SA1",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA2")) %>%
  mutate(cycle_exp = str_c (cycle_name, exp, sep = "_")) %>%
  filter(sample_name != "syn-02-5") %>%
  filter(sample_name != "syn-01-20") %>%
  mutate(cycle_name = fct_relevel(cycle_name, "ST1", "ST2", "SA-Sc","SA1","SA2")) %>%
  mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark")) %>%
  mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA-Sc_1", "SA-Sc_2", "SA1_3", "SA1_4", "SA1_5", "SA1_6", "SA2_11")) %>%
    mutate(depth_cat = fct_relevel(depth_cat, "SUR", "DCM")) %>%
    mutate(vial = fct_relevel(vial, "i", "A", "B", "C", "D"))


p <- long %>%
  # filter(vial_type != "dark") %>%
  mutate(Subclade = recode(Subclade, "VIb"= "Others", "Ic"= "Others", "II-WPC2"= "Others", "UC-A"= "Others",  "EnvA"= "Others", "EnvB"= "Others", "IX" = "Others"))  %>%
    complete(cycle_exp, vial, depth_cat) %>%
  ggplot(aes(x=vial, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(panel.spacing.y = unit(0,"lines"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              strip.background = element_blank(),
              panel.border = element_rect(colour = "black", fill = NA),
              strip.text.y.right = element_text(angle = 0),
        legend.position = "bottom")+
#  theme(text=element_text(size=10),
#              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(depth_cat~cycle_exp, scales = "free_x") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force) +
  ylab("Proportion of reads")

p

pdf("supp_syn_vials.pdf", height=6, width=8) ; plot(p) ; dev.off()

```


# Figure S11- Sorted pico
## Read data
remove heterotrophs and 2 samples 
also removing 
```{r}
source(here("3_Phyloseq output and figures", "init_files", "read_pico.R"))

#Assign trophic mode and remove heterotrophics that are not dinophyceae
ps_pico <- phyloseq_assign_trophic(ps_pico) %>%
    subset_taxa(trophic_mode_2 != "heterotrophic")

# Do normalizations and transformation
ps_pico <- phyloseq_normalize_median(ps_pico)
long_pico <- phyloseq_transform_to_long(ps_pico) %>%
    filter(!(file_code %in% c("pico-01-30", "pico-15"))) #filter problem samples


#create levels for factors
long_pico <- long_pico %>%
    mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA-Sc_1", "SA-Sc_2", "SA1_3", "SA1_4", "SA1_5", "SA1_6", "SA2_11")) %>%
    mutate(trophic_mode_2 = fct_relevel(trophic_mode_2, "photosynthetic", "mixotrophic", "dinophyceae")) %>%
    mutate(cycle_name_2 = fct_relevel(cycle_name_2, "ST1", "ST2", "SA-Sc", "SA1", "SA2")) %>%
    mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark")) %>%
    mutate(depth_cat = fct_relevel(SAMPLE, "SUR", "DCM")) %>%
    mutate(vial = fct_relevel(vial, "i", "A", "B", "C", "D"))

```

## dataframe prep
```{r}
# pivot longer dataframe
otu_rel_abund <- long_pico %>%
    group_by(file_code) %>%
    mutate(rel_abund = n_reads / sum(n_reads)) %>%
    ungroup() %>%
    select(-n_reads) %>%
    pivot_longer(cols = asv_code:species,
                 names_to = "level",
                 values_to = "taxon") 
#group by the level you want to plot, calculate percent abundance
taxon_rel_abund <- otu_rel_abund %>%
    filter(level == "class") %>% #choose level here 
        mutate(taxon = case_when(taxon == 'Mamiellophyceae' ~ 'Mamiellophyceae',
                                 taxon == 'Chloropicophyceae' ~ 'Chloropicophyceae',
                                 taxon == 'Prymnesiophyceae' ~ 'Prymnesiophyceae',
                                # taxon == 'Bacillariophyta' ~ 'Bacillariophyta',
                                 #taxon == 'Bolidophyceae' ~ 'Bolidophyceae',
                                 taxon == 'Pelagophyceae' ~'Pelagophyceae',
                                 taxon == "Chrysophyceae" ~ 'Chrysophyceae',
                              #   taxon == 'Dinophyceae' ~'Dinophyceae',
                                 TRUE~ 'Other')) 

p <- taxon_rel_abund %>%
    complete(cycle_exp, vial, depth_cat) %>%
    mutate(taxon = fct_relevel(taxon, c("Mamiellophyceae", "Chloropicophyceae", "Prymnesiophyceae", "Pelagophyceae","Chrysophyceae", "Others"))) %>%
  ggplot(aes(x=vial, y=rel_abund, color=taxon, fill=taxon)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(panel.spacing.y = unit(0,"lines"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              strip.background = element_blank(),
              panel.border = element_rect(colour = "black", fill = NA),
              strip.text.y.right = element_text(angle = 0),
        legend.position = "bottom")+
#  theme(text=element_text(size=10),
#              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(depth_cat~cycle_exp, scales = "free_x") +
        scale_color_manual(values=colours_18s_class, limits = force) + 
        scale_fill_manual(values=colours_18s_class, limits = force) +
  ylab("Proportion of reads") +
  labs(fill = "Class",
       color = "Class")

p

pdf("supp_pico_vials.pdf", height=6, width=8) ; plot(p) ; dev.off()

```

```{r}
p <- long_pico %>%
  # mutate(Subclade = recode(Subclade, "VIb"= "Others", "Ic"= "Others", "II-WPC2"= "Others", "UC-A"= "Others",  "EnvA"= "Others", "EnvB"= "Others"))  %>%
    complete(cycle_exp, vial, depth_cat) %>%
  mutate(class = fct_lump_n(class, 6, other_level = "Others")) %>%
    mutate(class = fct_relevel(class, c("Mamiellophyceae", "Chloropicophyceae", "Prymnesiophyceae", "Bacillariophyta", "Pelagophyceae", "Others"))) %>%
  ggplot(aes(x=vial, y=n_reads, color=class, fill=class)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(panel.spacing.y = unit(0,"lines"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              strip.background = element_blank(),
              panel.border = element_rect(colour = "black", fill = NA),
              strip.text.y.right = element_text(angle = 0),
        legend.position = "right")+
#  theme(text=element_text(size=10),
#              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(depth_cat~cycle_exp, scales = "free_x") +
        scale_color_manual(values=colours_18s_class, limits = force) + 
        scale_fill_manual(values=colours_18s_class, limits = force) +
  ylab("Proportion of reads")

p

pdf("supp_pico_vials.pdf", height=5.5, width=8) ; plot(p) ; dev.off()
```


# Figure S12 - Sorted nano
## Read data
```{r}
source(here("3_Phyloseq output and figures", "init_files", "read_nano.R"))

#assign trophic mode and remove heterotrophics that are not dinophyceae
ps_nano <- phyloseq_assign_trophic(ps_nano)%>%
    subset_taxa(trophic_mode_2 != "heterotrophic")

# Do normalizations and long form, remove few samples.
ps_nano <- phyloseq_normalize_median(ps_nano)
long_nano <- phyloseq_transform_to_long(ps_nano) %>%
    filter(!(file_code %in% c("nano-12"))) 

#order all the factors
long_nano <- long_nano %>%
  mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA-Sc_1", "SA-Sc_2", "SA1_3", "SA1_4", "SA1_5", "SA1_6", "SA2_11")) %>%
  mutate(trophic_mode = fct_relevel(trophic_mode, "photosynthetic", "mixotrophic"))  %>%
  mutate(trophic_mode_2 = fct_relevel(trophic_mode_2, "photosynthetic", "mixotrophic",  "dinophyceae"))  %>%
  mutate(cycle_name_2 =  fct_relevel(cycle_name_2,"ST1", "ST2", "SA-Sc", "SA1", "SA2"))  %>%
  mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark"))%>%
  mutate(depth_cat = fct_relevel(SAMPLE, "SUR", "DCM")) %>%
    mutate(vial = fct_relevel(vial, "i", "A", "B", "C", "D"))
```

## prepare data frame
```{r}
# pivot longer dataframe
otu_rel_abund <- long_nano %>%
    group_by(file_code) %>%
    mutate(rel_abund = n_reads / sum(n_reads)) %>%
    ungroup() %>%
    select(-n_reads) %>%
    pivot_longer(cols = asv_code:species,
                 names_to = "level",
                 values_to = "taxon") 
```

```{r}
#group by the level you want to plot, calculate percent abundance
taxon_rel_abund <- otu_rel_abund %>%
    filter(level == "order") %>% #choose level here 
        mutate(taxon = case_when(taxon == 'Cryptomonadales' ~ 'Cryptomonadales',
                                 taxon == 'Dinophyceae_X' ~ 'Dinophyceae_X',
                                 # taxon == 'Suessiales' ~ 'Suessiales',
                                 taxon == 'Gymnodiniales' ~ 'Gymnodiniales', 
                                 # taxon == 'Bolidophyceae' ~ 'Bolidophyceae',
                                 taxon == 'Peridiniales' ~'Peridiniales',
                                 taxon == 'Prorocentrales' ~ 'Prorocentrales',
                                 taxon == 'Isochrysidales' ~'Isochrysidales',
                                 taxon == 'Prymnesiales' ~'Prymnesiales',
                                 taxon == 'Phaeocystales' ~'Phaeocystales',
                                 taxon == 'Bacillariophyta_X' ~'Bacillariophyta_X',
                                 taxon == 'Haptophyta_Clade_HAP3_X' ~'Haptophyta_Clade_HAP3_X',
                                 TRUE~ 'Other')) 


p <- taxon_rel_abund %>%
    complete(cycle_exp, vial, depth_cat) %>%
    mutate(taxon = fct_relevel(taxon, c("Bacillariophyta_X","Cryptomonadales",
                        "Prorocentrales","Peridiniales","Gymnodiniales","Dinophyceae_X",
                      "Haptophyta_Clade_HAP3_X", "Prymnesiales",
                        "Phaeocystales","Isochrysidales",
                        "Others"))) %>%
  ggplot(aes(x=vial, y=rel_abund, color=taxon, fill=taxon)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(panel.spacing.y = unit(0,"lines"),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              strip.background = element_blank(),
              panel.border = element_rect(colour = "black", fill = NA),
              strip.text.y.right = element_text(angle = 0),
        legend.position = "bottom")+
 # theme(text=element_text(size=10),
#              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(depth_cat~cycle_exp, scales = "free_x") +
        scale_color_manual(values=colours_18s_order, limits = force) + 
        scale_fill_manual(values=colours_18s_order, limits = force) +
  ylab("Proportion of reads") +
  labs(fill = "Order",
       color = "Order")

p


pdf("supp_nano_vials.pdf", height=6, width=8) ; plot(p) ; dev.off()
```