---
title: "test"
author: "Denise Ong"
date: "12/12/2022"
output: html_document
---
# Initialize
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(here)
source(here("phyloseq", "init_files", "init.R")) #for libraries
source(here("phyloseq", "init_files", "init_markdown.R")) #for markdown libraries
source(here("phyloseq", "init_files", "define_functions.R")) #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps 
source(here("phyloseq", "init_files", "colours_18sv4.R")) # predetermined colours
#source(here("phyloseq", "init_files", "colours_random.R")) #random colours
source(here("phyloseq", "trophic_mode", "trophic_function.R"))  # Function to assign trophic function for phyloseq objects. 2 
source(here("phyloseq", "init_files", "top_taxa_func.R")) #Function to select top taxa
library(ggtext)
library(ggforestplot)
# Colours
colours_cycle <- readxl::read_excel(here("phyloseq", "init_files","colours_cycle.xlsx"))
colours_cycle <- structure(colours_cycle$colour,.Names=colours_cycle$cycle)
```

list of species from sorted pico and nano with low abundance. 
# Sorted pico
## Read data
remove heterotrophs and 2 samples 
also removing 
```{r}
source(here("phyloseq", "init_files", "read_pico.R"))

#Assign trophic mode and remove heterotrophics that are not dinophyceae
ps_pico <- phyloseq_assign_trophic(ps_pico) %>%
    subset_taxa(trophic_mode_2 != "heterotrophic")

# Do normalizations and transformation
ps_pico <- phyloseq_normalize_median(ps_pico)
long_pico <- phyloseq_transform_to_long(ps_pico) %>%
    filter(!(file_code %in% c("pico-01-30", "pico-15"))) %>% #filter problem samples
    filter(!(cycle_exp =="SA1_2" & SAMPLE == "DCM")) %>% #only intials in these experiments
    filter(!(cycle_exp == "SA1_1" & SAMPLE == "DCM")) 

#create levels for factors
long_pico <- long_pico %>%
    mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA1_1", "SA1_2", "SA2_3", "SA2_4", "SA2_5", "SA2_6", "SA3_11")) %>%
    mutate(trophic_mode_2 = fct_relevel(trophic_mode_2, "photosynthetic", "mixotrophic", "dinophyceae")) %>%
    mutate(cycle_name_2 = fct_relevel(cycle_name_2, "ST1", "ST2", "SA1", "SA2", "SA3")) %>%
    mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark")) %>%
    mutate(depth_cat = fct_relevel(SAMPLE, "SUR", "DCM"))

```

## dataframe prep
```{r}

long_pico_1 <- long_pico %>%
   #  ps_top_asv(10) %>% #subset top 10 ASVs per sample
     filter(vial_type=="light")


# pivot longer dataframe
otu_rel_abund <- long_pico_1 %>%
    group_by(file_code) %>%
    mutate(rel_abund = n_reads / sum(n_reads)) %>%
    ungroup() %>%
    select(-n_reads) %>%
    pivot_longer(cols = asv_code:species,
                 names_to = "level",
                 values_to = "taxon") 
# for log scale
# nseqs_per_sample <- otu_rel_abund %>%
#     group_by(file_code) %>%
#     summarise(N=sum(rel_abund)) %>%
#     count(N) %>%
#     pull(N)
# 
# lod <- 1/nseqs_per_sample

```

## species - select median >5% for any cycle
```{r}
taxon_rel_abund <- otu_rel_abund %>%
    filter(level == "species") %>% #choose level here 
    group_by(cycle_name_2, file_code, taxon) %>%
    summarise(rel_abund = 100*sum(rel_abund)) %>%
    pivot_wider(names_from = taxon, values_from = rel_abund) %>% #from here is to replace any file_code with NA as 0
    replace(., is.na(.), 0) %>%
    pivot_longer(cols= !cycle_name_2:file_code,
                 names_to = "taxon",
                 values_to = "rel_abund")

pico_taxon_pool <- taxon_rel_abund %>%
    group_by(cycle_name_2, taxon) %>%
    summarise(median = median(rel_abund)) %>% #calculate median proportion of reads per sp per cycle
    group_by(taxon) %>%
    summarise(pool = max(median) <= 5, #species with a max median proportion of reads in any cycle < 5% is under Others
              median = max(median),
              .groups = "drop") %>%
    filter(pool == FALSE)
```

# Sorted nano
## Read data
```{r}
source(here("phyloseq", "init_files", "read_nano.R"))

#assign trophic mode and remove heterotrophics that are not dinophyceae
ps_nano <- phyloseq_assign_trophic(ps_nano)%>%
    subset_taxa(trophic_mode_2 != "heterotrophic")

# Do normalizations and long form, remove few samples.
ps_nano <- phyloseq_normalize_median(ps_nano)
long_nano <- phyloseq_transform_to_long(ps_nano) %>%
    filter(!(file_code %in% c("nano-12"))) 

#order all the factors
long_nano <- long_nano %>%
  mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA1_1", "SA1_2", "SA2_3", "SA2_4", "SA2_5", "SA2_6", "SA3_11")) %>%
  mutate(trophic_mode = fct_relevel(trophic_mode, "photosynthetic", "mixotrophic"))  %>%
  mutate(trophic_mode_2 = fct_relevel(trophic_mode_2, "photosynthetic", "mixotrophic",  "dinophyceae"))  %>%
  mutate(cycle_name_2 =  fct_relevel(cycle_name_2,"ST1", "ST2", "SA1", "SA2", "SA3"))  %>%
  mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark"))
```
## prepare data frame
```{r}

long_nano_1 <- long_nano %>%
   #  ps_top_asv(10) %>% #subset top 10 ASVs per sample
     filter(vial_type=="light")


# pivot longer dataframe
otu_rel_abund <- long_nano_1 %>%
    group_by(file_code) %>%
    mutate(rel_abund = n_reads / sum(n_reads)) %>%
    ungroup() %>%
    select(-n_reads) %>%
    pivot_longer(cols = asv_code:species,
                 names_to = "level",
                 values_to = "taxon") 
```

## Species - median  select 5% minimum
```{r}
taxon_rel_abund <- otu_rel_abund %>%
    filter(level == "species") %>% #choose level here 
    group_by(cycle_name_2, file_code, taxon) %>%
    summarise(rel_abund = 100*sum(rel_abund)) %>%
    pivot_wider(names_from = taxon, values_from = rel_abund) %>% #from here is to replace any file_code with NA as 0
    replace(., is.na(.), 0) %>%
    pivot_longer(cols= !cycle_name_2:file_code,
                 names_to = "taxon",
                 values_to = "rel_abund")

nano_taxon_pool <- taxon_rel_abund %>%
    group_by(cycle_name_2, taxon) %>%
    summarise(median = mean(rel_abund)) %>% #calculate median proportion of reads per sp per cycle
    group_by(taxon) %>%
    summarise(pool = max(median) <= 5, #species with a max median proportion of reads in any cycle < 5% is under Others
              median = max(median),
              .groups = "drop") %>%
    filter(pool= FALSE)

taxon_pool <- full_join(pico_taxon_pool,nano_taxon_pool) %>%
    select(taxon) %>%
    rename(species = taxon)
```

# Filt read data
```{r}
source(here("phyloseq", "init_files", "read_18s_filt_sort.R"))

ps_filt_sort <- phyloseq_assign_trophic(ps_filt_sort) %>%
    subset_taxa(trophic_mode_2 != "heterotrophic") #remove heterotrophs
# Do normalizations and transformation
ps_filt_sort <- phyloseq_normalize_median(ps_filt_sort)
long_filt_sort <- phyloseq_transform_to_long(ps_filt_sort) %>%
  mutate(cycle_name_2 = fct_relevel(cycle_name_2, "ST1", "ST2", "SA1", "SA2", "SA3")) %>%
  mutate(sample = fct_relevel(sample, "SUR", "DCM"))
```

```{r}
long_filt<- long_filt_sort %>%
    filter(sample_type == "filt")

long_filt_anti <- anti_join(long_filt, taxon_pool) %>%
  distinct() %>%
  # mutate(in_sorted = "no") %>%
    mutate(in_sorted = case_when(class == "Dinophyceae" ~ "dinophyceae",
                               TRUE~ "no"))  %>%
  filter(class != "Syndiniales") %>%
  filter(species != "Dinophyceae_XXX_sp.") %>%
  filter(trophic_mode == "photosynthetic") 

long_filt_sort <- inner_join(long_filt, taxon_pool) %>%
    distinct() %>%
  mutate(in_sorted = "yes")


long_filt_sort_join <- full_join(long_filt_anti, long_filt_sort) %>%
  filter(class != "Syndiniales") %>%
  filter(species != "Dinophyceae_XXX_sp.") %>%
  filter(trophic_mode == "photosynthetic") 

# check proportion of photosynthetic not in sorted
p  <- long_filt_sort_join %>%
  ggplot(aes(x=station, y=n_reads, fill=in_sorted, colour = in_sorted)) +
  geom_bar(position="fill", stat="identity", size=0.5) + 
        theme(text=element_text(size=10),
              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(.~cycle_name_2, scales = "free_x") 
p

# check proportion of dinophyceae
p  <- long_filt_anti %>%
  ggplot(aes(x=station, y=n_reads, fill=trophic_mode_2, colour = trophic_mode_2)) +
  geom_bar(position="fill", stat="identity", size=0.5) + 
        theme(text=element_text(size=10),
              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(.~cycle_name_2, scales = "free_x") 
p

#check composition of not sorted
p1 <- long_filt_anti %>%
  filter(trophic_mode_2 !="dinophyceae") %>%
  mutate(order = fct_lump_n(order, 13, other_level = "Others")) %>%
#  ps_top(class, 8) %>%
  #mutate(class = fct_infreq(class)) %>%
  ggplot(aes(x=station, y=n_reads, fill=order, colour = order)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        theme(text=element_text(size=10),
              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(.~cycle_name_2, scales = "free_x") +
        ggtitle("Filtered photosynthetic - not in sorted") +
        scale_color_manual(values=orderPalette, limits = force) +
        scale_fill_manual(values=orderPalette, limits = force) +
  ylab("Proportion of reads")
p1


#check diatoms
for (i in c("Bacillariophyta_X", "Chloropicales", "Cryptomonadales", "Dictyochophyceae_X", "Isochrysidales","Mamiellales", "Pelagomonadales", "Phaeocystales" )) {
p <- long_filt_anti %>%
  filter(order == i) %>%
  mutate(species = fct_lump_n(species, 10, other_level = "Others")) %>%
#  ps_top(class, 8) %>%
  #mutate(class = fct_infreq(class)) %>%
  ggplot(aes(x=station, y=n_reads, fill=species, colour = species)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        theme(text=element_text(size=10),
              axis.text.x = element_text(angle = 45, hjust = 1))+
        facet_grid(.~cycle_name_2, scales = "free_x") +
        ggtitle(str_c("Filtered photosynthetic - not in sorted -", i)) +
        scale_color_manual(values=speciesPalette, limits = force) +
        scale_fill_manual(values=speciesPalette, limits = force) +
  ylab("Proportion of reads")
print(p)
}
```
