---
title: "20220417_sorted euks"
author: "Denise Ong"
date: "4/17/2022"
output: html_document
---

# Initialize
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(here)
source(here("phyloseq", "init_files", "init.R")) #for libraries
source(here("phyloseq", "init_files", "init_markdown.R")) #for markdown libraries
source(here("phyloseq", "init_files", "define_functions.R")) #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps 
source(here("phyloseq", "init_files", "colours_18sv4.R")) # predetermined colours
#source(here("phyloseq", "init_files", "colours_random.R")) #random colours
source(here("phyloseq", "trophic_mode", "trophic_function.R"))  # Function to assign trophic function for phyloseq objects. 2 
source(here("phyloseq", "init_files", "top_taxa_func.R")) #Function to select top taxa
```

# Sorted pico
## Read data
remove heterotrophs and 2 samples 
also removing 
```{r}
source(here("phyloseq", "init_files", "read_pico.R"))

#Assign trophic mode and remove heterotrophics that are not dinophyceae
ps_pico <- phyloseq_assign_trophic(ps_pico) %>%
    subset_taxa(trophic_mode_2 != "heterotrophic")

# Do normalizations and transformation
ps_pico <- phyloseq_normalize_median(ps_pico)
long_pico <- phyloseq_transform_to_long(ps_pico) %>%
    filter(!(file_code %in% c("pico-01-30", "pico-15"))) %>% #filter problem samples
    filter(!(cycle_exp =="SA1_2" & SAMPLE == "DCM")) %>% #only intials in these experiments
    filter(!(cycle_exp == "SA1_1" & SAMPLE == "DCM")) 

#create levels for factors
long_pico <- long_pico %>%
    mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA1_1", "SA1_2", "SA2_3", "SA2_4", "SA2_5", "SA2_6", "SA3_11")) %>%
    mutate(trophic_mode_2 = fct_relevel(trophic_mode_2, "photosynthetic", "mixotrophic", "dinophyceae")) %>%
    mutate(cycle_name_2 = fct_relevel(cycle_name_2, "ST1", "ST2", "SA1", "SA2", "SA3")) %>%
    mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark")) %>%
    mutate(depth_cat = fct_relevel(SAMPLE, "SUR", "DCM"))

```

## plot number of ASVs per sample
average number of ASVs per sample is 20.
```{r}
pico_asv <- long_pico %>%
    select(file_code, asv_code) %>%
    group_by(file_code) %>%
    summarise(n = n())
hist(pico_asv$n)
mean(pico_asv$n)
```
## barplot at class level
```{r}
#subset top 10 ASVs per sample, only surface samples
long_pico_1 <- long_pico %>%
    ps_top_asv(10)

# all
p <-  long_pico_1 %>%
    filter(SAMPLE=="SUR") %>%
    complete(cycle_exp, vial_type, SAMPLE) %>%
    filter(!(cycle_exp =="SA1_2")) %>% 
   # mutate(class = fct_lump_n(class, 7, other_level = "Others")) %>%
    mutate(class = fct_relevel(class, c("Mamiellophyceae", "Chloropicophyceae", "Pyramimonadophyceae", "Trebouxiophyceae", "Prymnesiophyceae", "Haptophyta_Clade_HAP3", "Bolidophyceae", "Bacillariophyta", "Chrysophyceae", "Dictyochophyceae", "Pelagophyceae", "MOCH-2","Dinophyceae", "Prasinodermophyceae", "Cryptophyceae"))) %>%
  #mutate(class = fct_relevel(class, c("Mamiellophyceae", "Chloropicophyceae", "Prymnesiophyceae", "Haptophyta_Clade_HAP3", "Bolidophyceae", "Bacillariophyta", "Chrysophyceae",  "Pelagophyceae", "Dinophyceae", "Cryptophyceae"))) %>%
  ggplot(aes(x=vial_type, y=n_reads, fill=class)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_exp, scales = "free_x") +
        ggtitle("Sorted pico - class level") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=colours_18s_class, limits = force) +
  ylab("Proportion of reads")
p
pdf(here("phyloseq", "paper_c14", "20220417", "pico", "pico_class_sur.pdf"), height=5, width=8) ; plot(p) ; dev.off()

#average of each cycle
p <-  long_pico_1 %>%
    filter(SAMPLE=="SUR") %>%
    filter(!(cycle_exp =="SA1_2")) %>% 
    complete(cycle_exp, vial_type, SAMPLE) %>%
    drop_na(cycle_name_2) %>%
    filter(vial_type != "dark") %>%
    mutate(class = fct_lump_n(class, 7, other_level = "Others")) %>%
    #mutate(class = fct_relevel(class, c("Mamiellophyceae", "Chloropicophyceae", "Pyramimonadophyceae", "Trebouxiophyceae", "Prymnesiophyceae", "Haptophyta_Clade_HAP3", "Bolidophyceae", "Bacillariophyta", "Chrysophyceae", "Dictyochophyceae", "Pelagophyceae", "MOCH-2","Dinophyceae", "Prasinodermophyceae", "Cryptophyceae"))) %>%
  mutate(class = fct_relevel(class, c("Chloropicophyceae", "Mamiellophyceae", "Pyramimonadophyceae", "Dinophyceae", "Bolidophyceae", "Chrysophyceae", "Pelagophyceae", "Prymnesiophyceae", "Others"))) %>%
  ggplot(aes(x=vial_type, y=n_reads, fill=class, colour=class)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_name_2, scales = "free_x") +
        ggtitle("Sorted pico") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        scale_fill_manual(values=colours_18s_class, limits = force) +
    scale_colour_manual(values=colours_18s_class, limits = force)+
  ylab("Proportion of reads")
p
pdf(here("phyloseq", "paper_c14", "20220417", "pico", "pico_cycle_avg.pdf"), height=5, width=8) ; plot(p) ; dev.off()

#pick one experiment per cycle
p <-  long_pico_1 %>%
    filter(SAMPLE=="SUR") %>%
    complete(cycle_exp, vial_type, SAMPLE) %>%
    filter(cycle_exp %in% c("ST1_8",  "ST2_9", "SA1_1", "SA2_6",  "SA3_11"))  %>%
    filter(vial_type != "dark") %>%
   # mutate(class = fct_lump_n(class, 7, other_level = "Others")) %>%
    #mutate(class = fct_relevel(class, c("Mamiellophyceae", "Chloropicophyceae", "Pyramimonadophyceae", "Trebouxiophyceae", "Prymnesiophyceae", "Haptophyta_Clade_HAP3", "Bolidophyceae", "Bacillariophyta", "Chrysophyceae", "Dictyochophyceae", "Pelagophyceae", "MOCH-2","Dinophyceae", "Prasinodermophyceae", "Cryptophyceae"))) %>%
  mutate(class = fct_relevel(class, c("Chloropicophyceae", "Mamiellophyceae", "Pyramimonadophyceae", "Dinophyceae","Bacillariophyta", "Dictyochophyceae", "Bolidophyceae", "Chrysophyceae", "Pelagophyceae", "Prymnesiophyceae"))) %>%
  ggplot(aes(x=vial_type, y=n_reads, fill=class, colour=class)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_exp, scales = "free_x") +
        ggtitle("Sorted pico - class level") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=colours_18s_class, limits = force) +
        scale_colour_manual(values=colours_18s_class, limits = force) +
        ylab("Proportion of reads")
p
pdf(here("phyloseq", "paper_c14", "20220417", "pico", "pico_class_select.pdf"), height=5, width=8) ; plot(p) ; dev.off()
```

## species for each class 
```{r}
class_vector <- long_pico_1 %>%
    select(class) %>%
    distinct() 
class_list <- list(class_vector$class)

for (i in c("Mamiellophyceae", "Prymnesiophyceae", "Pelagophyceae", "Chrysophyceae", "Bolidophyceae", "Chloropicophyceae", "Bacillariophyta", "Trebouxiophyceae", "Dictyochophyceae", "Pyramimonadophyceae")) {   
    long_pico_1$species_sub <- long_pico_1$species
    long_pico_1$species_sub<-ifelse(long_pico_1$class==i,long_pico_1$species_sub, "Others")
    p <-  long_pico_1 %>%
        mutate(species_sub = fct_infreq(species_sub)) %>%
        mutate(SAMPLE = fct_relevel(SAMPLE, "SUR", "DCM")) %>%
        complete(cycle_exp, vial_type, SAMPLE) %>%
        drop_na(SAMPLE) %>%
        mutate(species_sub = fct_infreq(species_sub)) %>%
        ggplot(aes(x=vial_type, y=n_reads, fill=species_sub)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(SAMPLE~cycle_exp, scales = "free_x") +
        ggtitle("Sorted pico species") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        ggtitle(str_c("Sorted Pico -", i)) +
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=speciesPalette, limits = force) +
        ylab("Proportion of reads")
    print(p)
    pdf(here("phyloseq", "paper_c14", "20220417", "pico", "class", str_c("Pico species_", i, ".pdf")), height=5, width=8) ; plot(p) ; dev.off()
}

for (i in c("Mamiellophyceae", "Prymnesiophyceae", "Pelagophyceae", "Chrysophyceae", "Bolidophyceae", "Chloropicophyceae", "Bacillariophyta", "Trebouxiophyceae", "Dictyochophyceae", "Pyramimonadophyceae")) {   
    long_pico_1$species_sub <- long_pico_1$species
    long_pico_1$species_sub<-ifelse(long_pico_1$class==i,long_pico_1$species_sub, "Others")
    p <-  long_pico_1 %>%
        mutate(species_sub = fct_infreq(species_sub)) %>%
        complete(cycle_exp, vial_type, SAMPLE) %>%
        filter(vial_type != "dark") %>%
        filter(SAMPLE=="SUR") %>%
        drop_na(cycle_name_2) %>%
        mutate(species_sub = fct_infreq(species_sub)) %>%
        ggplot(aes(x=vial_type, y=n_reads, fill=species_sub, colour = species_sub)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_name_2, scales = "free_x") +
        ggtitle("Sorted pico species") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        ggtitle(str_c("Sorted Pico -", i)) +
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=speciesPalette, limits = force) +
        scale_colour_manual(values=speciesPalette, limits = force) +
        ylab("Proportion of reads")
    print(p)
    pdf(here("phyloseq", "paper_c14", "20220417", "pico", "class", str_c("Pico surface species_", i, ".pdf")), height=5, width=8) ; plot(p) ; dev.off()
}
```


# Sorted nano
## Read data
```{r}
source(here("phyloseq", "init_files", "read_nano.R"))

#assign trophic mode and remove heterotrophics that are not dinophyceae
ps_nano <- phyloseq_assign_trophic(ps_nano)%>%
    subset_taxa(trophic_mode_2 != "heterotrophic")

# Do normalizations and long form, remove few samples.
ps_nano <- phyloseq_normalize_median(ps_nano)
long_nano <- phyloseq_transform_to_long(ps_nano) %>%
    filter(!(file_code %in% c("nano-12"))) 

#order all the factors
long_nano <- long_nano %>%
  mutate(cycle_exp = fct_relevel(cycle_exp, "ST1_7", "ST1_8", "ST2_9", "ST2_10", "SA1_1", "SA1_2", "SA2_3", "SA2_4", "SA2_5", "SA2_6", "SA3_11")) %>%
  mutate(trophic_mode = fct_relevel(trophic_mode, "photosynthetic", "mixotrophic"))  %>%
  mutate(trophic_mode_2 = fct_relevel(trophic_mode_2, "photosynthetic", "mixotrophic",  "dinophyceae"))  %>%
  mutate(cycle_name_2 =  fct_relevel(cycle_name_2,"ST1", "ST2", "SA1", "SA2", "SA3"))  %>%
  mutate(vial_type = fct_relevel(vial_type, "initial", "light", "dark"))
```


## plot number of ASVs per sample
```{r}
nano_asv <- long_nano %>%
    select(file_code,asv_code) %>%
    group_by(file_code) %>%
    summarise(n = n())
hist(nano_asv$n)
mean(nano_asv$n)
```

## barplot at  order level
```{r}
#subset top 15 ASVs per sample, only surface samples
long_nano_1 <- long_nano %>%
    ps_top_asv(15)
    
# plot  all
p <-  long_nano_1 %>%
    filter(SAMPLE=="SUR") %>%
    filter(!(cycle_exp =="SA1_2")) %>%
    complete(cycle_exp, vial_type, SAMPLE) %>%
    #mutate(order = fct_infreq(order)) %>%
    mutate(order = fct_lump_n(order, 15, other_level = "Others")) %>%
    mutate(order = factor(order, levels = c("Dolichomastigales", "Pyramimonadales","Cryptomonadales", "Dinophyceae_X", "Suessiales", "Gymnodiniales","Peridiniales", "Prorocentrales", "Isochrysidales", "Prymnesiales", "Phaeocystales","Syracosphaerales" , "Bacillariophyta_X", "Dictyochophyceae_X", "MOCH-2_X", "Nephroselmidales", "Haptophyta_Clade_HAP5", "Others"))) %>%
  ggplot(aes(x=vial_type, y=n_reads, fill=order)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_exp, scales = "free_x") +
        ggtitle("Sorted nano - class level") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=colours_18s_order, limits = force) +
  ylab("Proportion of reads")
p
pdf(here("phyloseq", "paper_c14", "20220417", "nano", "nano_class_sur.pdf"), height=5, width=8) ; plot(p) ; dev.off()

# plot average of each cycle
p <-  long_nano_1 %>%
    filter(SAMPLE=="SUR") %>%
    complete(cycle_exp, vial_type, SAMPLE) %>%
    filter(!(cycle_exp =="SA1_2")) %>%
    filter(vial_type!= "dark") %>%
    drop_na(cycle_name_2) %>%
    mutate(order = fct_infreq(order)) %>%
    mutate(order = fct_lump_n(order, 13, other_level = "Others")) %>%
    mutate(order = factor(order, levels = c("Chlorellales", "Cryptomonadales", "Dinophyceae_X", "Suessiales", "Gymnodiniales","Peridiniales", "Prorocentrales", "Isochrysidales", "Prymnesiales", "Phaeocystales","Syracosphaerales" , "Bacillariophyta_X", "Haptophyta_Clade_HAP3_X", "Others"))) %>%
  ggplot(aes(x=vial_type, y=n_reads, fill=order, colour=order)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_name_2, scales = "free_x") +
        ggtitle("Sorted nano - class level") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=colours_18s_order, limits = force) +
    scale_colour_manual(values=colours_18s_order, limits = force) +
  ylab("Proportion of reads")
p
pdf(here("phyloseq", "paper_c14", "20220417", "nano", "nano_cycle_avg.pdf"), height=5, width=8) ; plot(p) ; dev.off()

# plot selected experiments
p <-  long_nano_1 %>%
    complete(cycle_exp, vial_type, SAMPLE) %>%
    filter(SAMPLE=="SUR") %>%
    filter(cycle_exp %in% c("ST1_8",  "ST2_9", "SA1_1", "SA2_6",  "SA3_11"))  %>%
    filter(vial_type != "dark") %>%
    mutate(order = fct_infreq(order)) %>%
    mutate(order = fct_lump_n(order, 13, other_level = "Others")) %>%
    mutate(order = factor(order, levels = c("Chlorellales", "Cryptomonadales", "Dinophyceae_X", "Suessiales", "Gymnodiniales","Peridiniales", "Prorocentrales", "Isochrysidales", "Prymnesiales", "Phaeocystales","Syracosphaerales" , "Bacillariophyta_X", "Haptophyta_Clade_HAP3_X", "Others"))) %>%
  ggplot(aes(x=vial_type, y=n_reads, fill=order, colour=order)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(.~cycle_exp, scales = "free_x") +
        ggtitle("Sorted nano - class level") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=colours_18s_order, limits = force) +
    scale_colour_manual(values=colours_18s_order, limits = force) +
  ylab("Proportion of reads")
p
pdf(here("phyloseq", "paper_c14", "20220417", "nano", "nano_cycle_select.pdf"), height=5, width=8) ; plot(p) ; dev.off()
```

## species for each class 
```{r}
for (i in c("Pyramimonadales","Cryptomonadales", "Dinophyceae_X", "Suessiales", "Gymnodiniales","Peridiniales", "Prorocentrales", "Isochrysidales", "Prymnesiales", "Phaeocystales","Syracosphaerales" , "Bacillariophyta_X", "Dictyochophyceae_X")) {
    long_nano_1$species_sub <- long_nano_1$species
    long_nano_1$species_sub<-ifelse(long_nano_1$order==i,long_nano_1$species_sub, "Others")
    p <-  long_nano_1 %>%
        mutate(species_sub = fct_infreq(species_sub)) %>%
        drop_na(SAMPLE) %>%
        mutate(SAMPLE = fct_relevel(SAMPLE, "SUR", "DCM")) %>%
        complete(cycle_exp, vial_type,SAMPLE) %>%
        ggplot(aes(x=vial_type, y=n_reads, fill=species_sub)) + 
        geom_bar(position="fill", stat="identity", size=0.5) + 
        facet_grid(SAMPLE~cycle_exp, scales = "free_x") +
        ggtitle("Sorted nano species") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        ggtitle(str_c("Sorted Pico -", i)) +
        #scale_fill_manual(values=latin_palette('karolg', 15)) +
        scale_fill_manual(values=speciesPalette, limits = force) +
        ylab("Proportion of reads")
    print(p)
    pdf(here("phyloseq", "paper_c14", "20220417", "nano", "order", str_c("nano species_", i, ".pdf")), height=5, width=8) ; plot(p) ; dev.off()
}

```

