---
title: "20210929_petB_2x300"
author: "Denise Ong"
date: "9/29/2021"
output: html_document
---
# Initialize
```{r, echo=TRUE, message=FALSE, warning=FALSE}

source("phyloseq/init.R") #for libraries
source("phyloseq/init_markdown.R") #for markdown libraries
source("phyloseq/define_functions.R") #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps 
source("phyloseq/colours_petb.R") #colours
```

# Sorted syn -petB Denise primer -R1
## Read data
```{r}
# Load the phyloseq files
ps <- read_rds("output_petb_2x300/output_petb_Denise/R1/TAN1810_petB_nested_phyloseq_asv_set_sortedsyn.RDS") 

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps)$water_mass <- sample_data(ps)$Cycle.
sample_data(ps)$water_mass = str_replace(sample_data(ps)$water_mass, "1|2|5", "SA") 
sample_data(ps)$water_mass = str_replace(sample_data(ps)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps)$cycle_location <- sample_data(ps)$Cycle.
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "1", "C")
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "2", "D") 
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "5", "E") 
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "3", "A")
sample_data(ps)$cycle_location = str_replace(sample_data(ps)$cycle_location, "4", "B")

sample_data(ps)$cycle_name <- sample_data(ps)$Cycle.
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps)$cycle_name = str_replace(sample_data(ps)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps)$cycle_location_name <- str_c(sample_data(ps)$cycle_location, sample_data(ps)$cycle_name, sep ="_")

#vial type
sample_data(ps)$vial_type <- sample_data(ps)$vial
sample_data(ps)$vial_type = str_replace(sample_data(ps)$vial_type, "i", "initial") 
sample_data(ps)$vial_type = str_replace(sample_data(ps)$vial_type, "A|B|C", "light")
sample_data(ps)$vial_type = str_replace(sample_data(ps)$vial_type, "D", "dark")

# Remove ASVs that are not present in the dataset
ps <- ps %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps <- phyloseq_normalize_median(ps)
long <- phyloseq_transform_to_long(ps)
```

```{r}
p1 <- long %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "syn-negr1-2") %>%
    filter(sample_name != "syn-11") %>%
    filter(sample_name != "syn-12") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(text=element_text(size=5),
              axis.text.x = element_text(angle = 45, hjust = 1), 
              plot.title = element_text(size = 10), 
              legend.title =element_text(size= 7),
              legend.key.size = unit(0.5, 'cm'),
        strip.text.x = element_text(size = 7),
        legend.text = element_text(size=7))+ 
    #    facet_grid(.~water_mass, scales = "free_x") +
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("C14 sorted syn Denise primer- R1") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force) 
p1

pdf("phyloseq/figures_20210930/C14 syn Denise R1.pdf", height=5, width=8) ; plot(p) ; dev.off()
```

# Sorted syn -petB Denise primer -R2
## Read data
```{r}
# Load the phyloseq files
ps_sorted_R2 <- read_rds("output_petb_2x300/output_petb_Denise/R2/TAN1810_petB_nested_phyloseq_asv_set_sortedsyn.RDS") 

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_sorted_R2)$water_mass <- sample_data(ps_sorted_R2)$Cycle.
sample_data(ps_sorted_R2)$water_mass = str_replace(sample_data(ps_sorted_R2)$water_mass, "1|2|5", "SA") 
sample_data(ps_sorted_R2)$water_mass = str_replace(sample_data(ps_sorted_R2)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_sorted_R2)$cycle_location <- sample_data(ps_sorted_R2)$Cycle.
sample_data(ps_sorted_R2)$cycle_location = str_replace(sample_data(ps_sorted_R2)$cycle_location, "1", "C")
sample_data(ps_sorted_R2)$cycle_location = str_replace(sample_data(ps_sorted_R2)$cycle_location, "2", "D") 
sample_data(ps_sorted_R2)$cycle_location = str_replace(sample_data(ps_sorted_R2)$cycle_location, "5", "E") 
sample_data(ps_sorted_R2)$cycle_location = str_replace(sample_data(ps_sorted_R2)$cycle_location, "3", "A")
sample_data(ps_sorted_R2)$cycle_location = str_replace(sample_data(ps_sorted_R2)$cycle_location, "4", "B")

sample_data(ps_sorted_R2)$cycle_name <- sample_data(ps_sorted_R2)$Cycle.
sample_data(ps_sorted_R2)$cycle_name = str_replace(sample_data(ps_sorted_R2)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_sorted_R2)$cycle_name = str_replace(sample_data(ps_sorted_R2)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_sorted_R2)$cycle_name = str_replace(sample_data(ps_sorted_R2)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_sorted_R2)$cycle_name = str_replace(sample_data(ps_sorted_R2)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_sorted_R2)$cycle_name = str_replace(sample_data(ps_sorted_R2)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps_sorted_R2)$cycle_location_name <- str_c(sample_data(ps_sorted_R2)$cycle_location, sample_data(ps_sorted_R2)$cycle_name, sep ="_")

#vial type
sample_data(ps_sorted_R2)$vial_type <- sample_data(ps_sorted_R2)$vial
sample_data(ps_sorted_R2)$vial_type = str_replace(sample_data(ps_sorted_R2)$vial_type, "i", "initial") 
sample_data(ps_sorted_R2)$vial_type = str_replace(sample_data(ps_sorted_R2)$vial_type, "A|B|C", "light")
sample_data(ps_sorted_R2)$vial_type = str_replace(sample_data(ps_sorted_R2)$vial_type, "D", "dark")

# Remove ASVs that are not present in the dataset
ps_sorted_R2 <- ps_sorted_R2 %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_sorted_R2 <- phyloseq_normalize_median(ps_sorted_R2)
long_sorted_R2 <- phyloseq_transform_to_long(ps_sorted_R2)
```

```{r}
p2 <- long_sorted_R2 %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "syn-negr1-2") %>%
    filter(sample_name != "syn-11") %>%
    filter(sample_name != "syn-12") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(text=element_text(size=5),
              axis.text.x = element_text(angle = 45, hjust = 1), 
              plot.title = element_text(size = 10), 
              legend.title =element_text(size= 7),
              legend.key.size = unit(0.5, 'cm'),
        strip.text.x = element_text(size = 7),
        legend.text = element_text(size=7))+ 
    #    facet_grid(.~water_mass, scales = "free_x") +
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("C14 sorted syn Denise primer- R2") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force) 
p2

pdf("phyloseq/figures_20210930/C14 syn Denise R2.pdf", height=5, width=8) ; plot(p) ; dev.off()
```

# CTD-petB Denise primer-R1
##Read data
```{r}
# Load the phyloseq files
ps_ctd_nested <- read_rds("output_petb_2x300/output_petb_Denise/R1/TAN1810_petB_nested_phyloseq_asv_set_nestedCTD.RDS") 

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_ctd_nested)$water_mass <- sample_data(ps_ctd_nested)$cycle
sample_data(ps_ctd_nested)$water_mass = str_replace(sample_data(ps_ctd_nested)$water_mass, "1|2|5", "SA") 
sample_data(ps_ctd_nested)$water_mass = str_replace(sample_data(ps_ctd_nested)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_ctd_nested)$cycle_location <- sample_data(ps_ctd_nested)$cycle
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "1", "C")
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "2", "D") 
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "5", "E") 
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "3", "A")
sample_data(ps_ctd_nested)$cycle_location = str_replace(sample_data(ps_ctd_nested)$cycle_location, "4", "B")

sample_data(ps_ctd_nested)$cycle_name <- sample_data(ps_ctd_nested)$cycle
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_ctd_nested)$cycle_name = str_replace(sample_data(ps_ctd_nested)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps_ctd_nested)$cycle_location_name <- str_c(sample_data(ps_ctd_nested)$cycle_location, sample_data(ps_ctd_nested)$cycle_name, sep ="_")

# Remove ASVs that are not present in the dataset
ps_ctd_nested <- ps_ctd_nested %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_ctd_nested <- phyloseq_normalize_median(ps_ctd_nested)
long_ctd_nested <- phyloseq_transform_to_long(ps_ctd_nested)
```

```{r}
p3 <- long_ctd_nested %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "syn-negr1-2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(text=element_text(size=5),
              axis.text.x = element_text(angle = 45, hjust = 1), 
              plot.title = element_text(size = 10), 
              legend.title =element_text(size= 7),
              legend.key.size = unit(0.5, 'cm'),
        strip.text.x = element_text(size = 7),
        legend.text = element_text(size=7))+ 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB Denise primer-R1") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force)
p3

pdf("phyloseq/figures_20210930/CTD Denise R1.pdf", height=5, width=8) ; plot(p) ; dev.off()
```
# CTD-petB Denise primer-R2
##Read data
```{r}
# Load the phyloseq files
ps_ctd_nested_R2 <- read_rds("output_petb_2x300/output_petb_Denise/R2/TAN1810_petB_nested_phyloseq_asv_set_nestedCTD.RDS") 

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_ctd_nested_R2)$water_mass <- sample_data(ps_ctd_nested_R2)$cycle
sample_data(ps_ctd_nested_R2)$water_mass = str_replace(sample_data(ps_ctd_nested_R2)$water_mass, "1|2|5", "SA") 
sample_data(ps_ctd_nested_R2)$water_mass = str_replace(sample_data(ps_ctd_nested_R2)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_ctd_nested_R2)$cycle_location <- sample_data(ps_ctd_nested_R2)$cycle
sample_data(ps_ctd_nested_R2)$cycle_location = str_replace(sample_data(ps_ctd_nested_R2)$cycle_location, "1", "C")
sample_data(ps_ctd_nested_R2)$cycle_location = str_replace(sample_data(ps_ctd_nested_R2)$cycle_location, "2", "D") 
sample_data(ps_ctd_nested_R2)$cycle_location = str_replace(sample_data(ps_ctd_nested_R2)$cycle_location, "5", "E") 
sample_data(ps_ctd_nested_R2)$cycle_location = str_replace(sample_data(ps_ctd_nested_R2)$cycle_location, "3", "A")
sample_data(ps_ctd_nested_R2)$cycle_location = str_replace(sample_data(ps_ctd_nested_R2)$cycle_location, "4", "B")

sample_data(ps_ctd_nested_R2)$cycle_name <- sample_data(ps_ctd_nested_R2)$cycle
sample_data(ps_ctd_nested_R2)$cycle_name = str_replace(sample_data(ps_ctd_nested_R2)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_ctd_nested_R2)$cycle_name = str_replace(sample_data(ps_ctd_nested_R2)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_ctd_nested_R2)$cycle_name = str_replace(sample_data(ps_ctd_nested_R2)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_ctd_nested_R2)$cycle_name = str_replace(sample_data(ps_ctd_nested_R2)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_ctd_nested_R2)$cycle_name = str_replace(sample_data(ps_ctd_nested_R2)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps_ctd_nested_R2)$cycle_location_name <- str_c(sample_data(ps_ctd_nested_R2)$cycle_location, sample_data(ps_ctd_nested_R2)$cycle_name, sep ="_")

# Remove ASVs that are not present in the dataset
ps_ctd_nested_R2 <- ps_ctd_nested_R2 %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_ctd_nested_R2 <- phyloseq_normalize_median(ps_ctd_nested_R2)
long_ctd_nested_R2 <- phyloseq_transform_to_long(ps_ctd_nested_R2)
```

```{r}
p4 <- long_ctd_nested_R2 %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "syn-negr1-2") %>%
#  mutate(Subclade = fct_lump_n(Subclade, 12, other_level = "Others")) %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(text=element_text(size=5),
              axis.text.x = element_text(angle = 45, hjust = 1), 
              plot.title = element_text(size = 10), 
              legend.title =element_text(size= 7),
              legend.key.size = unit(0.5, 'cm'),
              strip.text.x = element_text(size = 7),
        legend.text = element_text(size=7))+ 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB Denise primer - R2") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force) 
p4

pdf("phyloseq/figures_20210930/CTD Denise R2.pdf", height=5, width=8) ; plot(p) ; dev.off()
```
# CTD- petB Mazard primer - R1
##Read data
```{r}
# Load the phyloseq files
ps_ctd_normal <- read_rds("output_petb_2x300/output_petb_Mazard/R1/TAN1810_petB_F-R_phyloseq_asv_set_CTDnormalR1.RDS")  # adding new component, this case the phyloseq object to the "tag" all

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_ctd_normal)$water_mass <- sample_data(ps_ctd_normal)$cycle
sample_data(ps_ctd_normal)$water_mass = str_replace(sample_data(ps_ctd_normal)$water_mass, "1|2|5", "SA") 
sample_data(ps_ctd_normal)$water_mass = str_replace(sample_data(ps_ctd_normal)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_ctd_normal)$cycle_location <- sample_data(ps_ctd_normal)$cycle
sample_data(ps_ctd_normal)$cycle_location = str_replace(sample_data(ps_ctd_normal)$cycle_location, "1", "C")
sample_data(ps_ctd_normal)$cycle_location = str_replace(sample_data(ps_ctd_normal)$cycle_location, "2", "D") 
sample_data(ps_ctd_normal)$cycle_location = str_replace(sample_data(ps_ctd_normal)$cycle_location, "5", "E") 
sample_data(ps_ctd_normal)$cycle_location = str_replace(sample_data(ps_ctd_normal)$cycle_location, "3", "A")
sample_data(ps_ctd_normal)$cycle_location = str_replace(sample_data(ps_ctd_normal)$cycle_location, "4", "B")

sample_data(ps_ctd_normal)$cycle_name <- sample_data(ps_ctd_normal)$cycle
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_ctd_normal)$cycle_name = str_replace(sample_data(ps_ctd_normal)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps_ctd_normal)$cycle_location_name <- str_c(sample_data(ps_ctd_normal)$cycle_location, sample_data(ps_ctd_normal)$cycle_name, sep ="_")
# Remove ASVs that are not present in the dataset
ps_ctd_normal <- ps_ctd_normal %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_ctd_normal <- phyloseq_normalize_median(ps_ctd_normal)
long_ctd_normal <- phyloseq_transform_to_long(ps_ctd_normal)
```

```{r}
p5 <- long_ctd_normal %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "CTD-petB-neg2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
        theme(text=element_text(size=5),
              axis.text.x = element_text(angle = 45, hjust = 1), 
              plot.title = element_text(size = 10), 
              legend.title =element_text(size= 7),
              legend.key.size = unit(0.5, 'cm'),
              strip.text.x = element_text(size = 7),
              legend.text = element_text(size=7))+ 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB Mazard primer - R1") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force) 
p5

pdf("phyloseq/figures_20210930/CTD Mazard R1.pdf", height=5, width=8) ; plot(p) ; dev.off()
```

# CTD- petB Mazard primer - R2
##Read data
```{r}
# Load the phyloseq files
ps_ctd_normal_R2 <- read_rds("output_petb_2x300/output_petb_Mazard/R2/TAN1810_petB_F-R_phyloseq_asv_set_CTD_petBF-R_R2.RDS")  # adding new component, this case the phyloseq object to the "tag" all

#copy the column of interest to create new column, and replacing names for water masses SA and ST
sample_data(ps_ctd_normal_R2)$water_mass <- sample_data(ps_ctd_normal_R2)$cycle
sample_data(ps_ctd_normal_R2)$water_mass = str_replace(sample_data(ps_ctd_normal_R2)$water_mass, "1|2|5", "SA") 
sample_data(ps_ctd_normal_R2)$water_mass = str_replace(sample_data(ps_ctd_normal_R2)$water_mass, "3|4", "ST")

#copy the column of interest, creating new column and replace for cycle names. Not using this column for now. 
sample_data(ps_ctd_normal_R2)$cycle_location <- sample_data(ps_ctd_normal_R2)$cycle
sample_data(ps_ctd_normal_R2)$cycle_location = str_replace(sample_data(ps_ctd_normal_R2)$cycle_location, "1", "C")
sample_data(ps_ctd_normal_R2)$cycle_location = str_replace(sample_data(ps_ctd_normal_R2)$cycle_location, "2", "D") 
sample_data(ps_ctd_normal_R2)$cycle_location = str_replace(sample_data(ps_ctd_normal_R2)$cycle_location, "5", "E") 
sample_data(ps_ctd_normal_R2)$cycle_location = str_replace(sample_data(ps_ctd_normal_R2)$cycle_location, "3", "A")
sample_data(ps_ctd_normal_R2)$cycle_location = str_replace(sample_data(ps_ctd_normal_R2)$cycle_location, "4", "B")

sample_data(ps_ctd_normal_R2)$cycle_name <- sample_data(ps_ctd_normal_R2)$cycle
sample_data(ps_ctd_normal_R2)$cycle_name = str_replace(sample_data(ps_ctd_normal_R2)$cycle_name, "1", "SA-Cycle_1")
sample_data(ps_ctd_normal_R2)$cycle_name = str_replace(sample_data(ps_ctd_normal_R2)$cycle_name, "2", "SA-Cycle_2") 
sample_data(ps_ctd_normal_R2)$cycle_name = str_replace(sample_data(ps_ctd_normal_R2)$cycle_name, "5", "SA-Cycle_5") 
sample_data(ps_ctd_normal_R2)$cycle_name = str_replace(sample_data(ps_ctd_normal_R2)$cycle_name, "3", "ST-Cycle_3")
sample_data(ps_ctd_normal_R2)$cycle_name = str_replace(sample_data(ps_ctd_normal_R2)$cycle_name, "4", "ST-Cycle_4")

sample_data(ps_ctd_normal_R2)$cycle_location_name <- str_c(sample_data(ps_ctd_normal_R2)$cycle_location, sample_data(ps_ctd_normal_R2)$cycle_name, sep ="_")
# Remove ASVs that are not present in the dataset
ps_ctd_normal_R2 <- ps_ctd_normal_R2 %>% 
    phyloseq::filter_taxa(function(x) sum(x) > 0 , TRUE) 

# Do normalizations and transformation
ps_ctd_normal_R2 <- phyloseq_normalize_median(ps_ctd_normal_R2)
long_ctd_normal_R2 <- phyloseq_transform_to_long(ps_ctd_normal_R2)
```

```{r}
p6 <- long_ctd_normal_R2 %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name != "CTD-petB-neg2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
  theme(text=element_text(size=5),
              axis.text.x = element_text(angle = 45, hjust = 1), 
              plot.title = element_text(size = 10), 
              legend.title =element_text(size= 7),
              legend.key.size = unit(0.5, 'cm'),
              strip.text.x = element_text(size = 7),
        legend.text = element_text(size=7))+ 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB Mazard primer - R2") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force)
  
p6

pdf("phyloseq/figures_20210930/CTD Mazard R2.pdf", height=5, width=8) ; plot(p) ; dev.off()
```

## Normal CTD negative
```{r}
p <- long_ctd_normal %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name == "CTD-petB-neg2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
        theme(text=element_text(size=10),axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB Mazard primer R1 negative") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force)
p

p <- long_ctd_normal_R2 %>%
   # mutate(Subclade = fct_infreq(Subclade))%>%
    filter(sample_name == "CTD-petB-neg2") %>%
  ggplot(aes(x=file_code, y=n_reads, color=Subclade, fill=Subclade)) + 
        geom_bar(position="fill", stat="identity") + 
        theme(text=element_text(size=10),axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_grid(.~cycle_location_name, scales = "free_x") +
        ggtitle("CTD petB Mazard primer R2 negative") +
        scale_color_manual(values=colours_petb_subclade, limits = force) + 
        scale_fill_manual(values=colours_petb_subclade, limits = force)
p

```

```{r}
library(cowplot)
g<- plot_grid(p1, p2, p3, p4, p5, p6, 
          labels = "AUTO", 
          ncol = 2,
          nrow = 3)
pdf("phyloseq/cowplot test.pdf", height=10, width=11) ; plot(g) ; dev.off()
```

