library(stringr)
library(ggplot2)
theme_set(theme_bw())
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(maps)
library(glue)
library(cowplot)
library(phyloseq)
library(forcats)
library(paletteer)

# library(pr2database)
# data("pr2")