---
title: "C14 NPP per population"
author: "Denise Ong"
date: "3/16/2021"
output: html_document
---
```{r setup, include=FALSE}
  knitr::opts_chunk$set(message=FALSE,
                        warning=FALSE,
                        cache=TRUE,
                        tidy=FALSE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
theme_set(
  theme_bw()
  )
library(broom)
```

error in TAN1810_14C-Pico_25052020_QA_1.0.xlsx, U1941 CHANGED TO U9141. excel sheet change to 1.2
Missing U9133
```{r}
fcm_raw <- readxl::read_xlsx("../data_used/MD FCM DATA.xlsx", skip = 2) %>%
  select(MD, CTD, DEPTH, `SYN/ML`, `PICO/mL`, `NANO/mL`) %>%
  dplyr::rename(ctd = `CTD`,
         depth = `DEPTH`,
         Syn = `SYN/ML`,
         Pico = `PICO/mL`,
         Nano = `NANO/mL`) %>% 
  pivot_longer(Syn:Nano, 
               names_to = "population",
               values_to = "conc") %>%
  filter(!is.na(conc))

pp_rates <- readxl::read_xlsx("../data_used/C14_rates per group.xlsx")

#use the "complete data TAN1810" sheet for the experiment details.
C14_hot <- readxl::read_excel("../data_used/TAN1810_14C-Pico_25052020_QA_1.2.xlsx", sheet = "Complete data TAN1810", skip = 11) %>%
  dplyr::select (`Cycle#`, `EXP#`, `SAMPLE`, `STN`, `DEPTH`, `CTD#`) %>%   
     dplyr::rename(cycle = `Cycle#`,
            exp = `EXP#`,
            sample = `SAMPLE`, 
            station = `STN`,
            depth = `DEPTH`,
            ctd = `CTD#`)%>%
    distinct()

C14_hot$cycle <- as.character(C14_hot$cycle) 
C14_hot$exp <- as.character(C14_hot$exp)

pp_rates <- full_join(pp_rates, C14_hot) %>%
  filter(!is.na(pp)) 

fcm <- left_join(pp_rates, fcm_raw) 

#calculate the mean conc for cycle 2, missing data for cycle 2 exp 5.
mean_conc <- fcm %>%
  filter(cycle == 2) %>%
  filter(sample == "SUR") %>%
  select(cycle, exp, sample,  population, conc) %>%
  group_by(cycle, sample, population) %>%
  summarise(mean_conc= mean(conc, na.rm = TRUE)) %>% 
  add_column(exp = 5)
mean_conc$exp <-as.character(mean_conc$exp)

#create new column, include mean conc for missing data
fcm_corrected <- full_join(mean_conc, fcm) %>%
  replace_na(list(mean_conc = 0, conc = 0)) %>%
  mutate(conc_corrected = mean_conc+ conc) %>%
  select(-mean_conc,  -conc)

#calculate npp per group
fcm_corrected$exp <- as.numeric(fcm_corrected$exp)
fcm_corrected <- fcm_corrected %>%
  arrange(exp) %>%
  mutate(conc_m3 = conc_corrected*10^6)%>% # change units from ml to m3
  mutate(npp = (pp*conc_m3*24*10^(-12))) # multiply by 24 to change from per hour to day, multiply by 10^-12 to convert from fg to mg
fcm_corrected$exp <- as.character(fcm_corrected$exp)

#arrange, add cycle names
fcm_corrected$population <- factor(fcm_corrected$population,levels = c("Syn", "Pico", "Nano")) 
fcm_corrected <- fcm_corrected%>% mutate(cycle_name = recode(cycle, "1" = "SA1",
                                    "2" = "SA2",
                                    "3" = "ST1",
                                    "4" = "ST2",
                                    "5" = "SA3"))

```

pp is fgC/h/cell
conc is no of cells/ml
npp units is mgC/m3/day

```{r}
npp <- fcm_corrected %>%
  group_by(cycle, sample, population) %>% 
  summarise(npp_mean = mean(npp,na.rm = TRUE))

writexl::write_xlsx(npp,"C14_npp per group.xlsx")

npp_total <-fcm_corrected %>%
  dplyr::group_by(cycle, exp, sample) %>%
  dplyr::summarise(npp_total = sum(npp,na.rm = TRUE))

writexl::write_xlsx(npp_total,"../data_used/C14_sum npp per group.xlsx")

npp_point <- fcm_corrected %>% 
  ggplot() +
  geom_point(aes(x= str_c(population,sample,  sep=" "), y = npp)) 

npp_boxplot <- fcm_corrected %>% 
  ggplot() +
  geom_boxplot(aes(x= str_c(population,sample,  sep=" "), y = npp)) 


npp_total
npp_boxplot
npp_point
```

```{r}
library(wesanderson)
fcm_corrected$cycle_name<-as.character(fcm_corrected$cycle_name)
fcm_corrected$cycle_name <- factor(fcm_corrected$cycle_name, levels = c("ST1", "ST2", "SA1", "SA2", "SA3"))

npp_cycle <- fcm_corrected %>%
  ggplot() +
  geom_boxplot(aes(y=npp, x= population , fill = population), show.legend = FALSE) + 
                 geom_point(aes(y=npp, x= population))+
                 facet_grid(.~cycle_name)+
  scale_fill_manual(values = c("#E69F00","#009E73","#D55E00")) +
  ylab("Net Primary Production\n(mgC/m3/day)")+
  xlab("Cycle")+
  scale_y_continuous(trans='log10')+
  annotation_logticks(sides = "l")+
  theme(axis.title=element_text(size=16),
        axis.text = element_text(size = 14),
        strip.text = element_text(size = 16))
png("../figures/C14_npp per group.png", width = 1200, height = 250)

npp_cycle
```
```{r}
cell_conc <- fcm_corrected %>%
  ggplot() +
  geom_boxplot(aes(y=conc_corrected, x= population , fill = population), show.legend = FALSE) +
                 geom_point(aes(y=conc_corrected, x= population))+
                 facet_grid(.~cycle_name)+
  scale_fill_manual(values = wes_palette("Darjeeling1", n = 3)) +
  ylab("Number of cells/ml") +
  xlab("Cycle")

png("../figures/cell conc.png", width = 600, height = 300)
cell_conc
```

#Function for summarising the data
```{r}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

# Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```
```{r}
conc_summary <- summarySE(fcm_corrected, measurevar="conc_corrected", groupvars=c("cycle_name", "population"), na.rm=TRUE)
conc_summary
conc_table <- conc_summary %>%
  select(cycle_name, population, conc_corrected, sd) %>%
  pivot_wider(names_from = population, values_from = conc_corrected:sd) %>%
  mutate(syn_pct=conc_corrected_Syn*100/(conc_corrected_Syn+conc_corrected_Pico))%>%
  mutate(pico_pct=conc_corrected_Pico*100/(conc_corrected_Syn+conc_corrected_Pico)) %>%
  mutate(pico_syn=)
conc_table


```
```{r}
conc_summary_depth <- summarySE(fcm_corrected, measurevar="conc_corrected", groupvars=c("cycle_name", "population","sample"), na.rm=TRUE)
conc_summary_depth
conc_table_depth <- conc_summary_depth %>%
select(cycle_name, population, sample, conc_corrected, sd) %>%
  pivot_wider(names_from = population:sample, values_from = conc_corrected:sd)
conc_table_depth
```

```{r}
npp_summary <- summarySE(fcm_corrected, measurevar="npp", groupvars=c("cycle_name", "population"), na.rm=TRUE)


npp_summary
```

```{r}
QE_table <- readxl::read_xlsx("../R/QE_table.xlsx")

library(xtable)
print(xtable(QE_table),
      comment = FALSE)
```

